6311 Горшенин
itsecd/ptm-2 pull request #1
Opened 2023-10-12 07:33 UTC by alxmcs

Этот классический пример kata для рефакторинга, помимо прочих своих проблем, нарушает кое-какой принцип построения приложений. Мне был хотелось, чтобы в ревью было указано, какой именно. Также хотелось бы увидеть предложения по модификации этого кода.

2023-10-16 21:15 UTC, dmgorshenin commented on accounts_manager.py
> +        self.accounts.append(BankAccount('Arthur', Decimal(800_000_000)))
cтоит улучшить код с инициализацией accounts в __init__

2023-10-16 21:17 UTC, dmgorshenin commented on accounts_manager.py
> +        )
нарушение PEP8: неправильная постановка отступов

2023-10-16 21:18 UTC, dmgorshenin commented on account.py
> +    def withdraw(self, amount):
отсутствует type_hinting

2023-10-16 21:20 UTC, dmgorshenin commented on accounts_manager.py
> +    def get_account_for_customer(self, customer_name: str):
отсутствует type-hinting в возвращаемом значении

2023-10-16 21:22 UTC, dmgorshenin commented on branch_finder.py
> +class BranchFinder:
нарушение PEP8: отсутствует пробел между импортами и классом

2023-10-16 21:23 UTC, dmgorshenin commented on branch.py
> +    def personal_accounts(self):
отсутствует type-hinting

2023-10-16 21:24 UTC, dmgorshenin commented on cash_machine.py
> +    def branch_finder(self):
отсутствует type-hinting

2023-10-16 21:28 UTC, dmgorshenin commented on cash_machine.py
> +            .withdraw(amount)
отсутствует открывающие и закрывающие скобки в return для явного указания продолжения цепочки
также нарушено выравнивание отступов

2023-10-16 21:36 UTC, dmgorshenin requested changes
В целом по коду:
- отсутствие докстрингов и в некоторых местах type-hint'ов
- класс CashMachine нарушает принципы SRP и DIP, так как он выполняет сразу несколько операций. Для улучшения кода следует принимать для инициализации BranchFinder, а не создавать его в отдельном методе, таким образом класс станет более гибким и будет соответствовать принципу DIP

2023-10-17 07:32 UTC, alxmcs reviewed
Было бы неплохо конкретизировать предлагаемые правки классов и пригляделся к коду еще раз

2023-10-17 07:32 UTC, alxmcs commented on cash_machine.py
> +        return self.branch_finder
На строках 11 -15 явно заметно нарушение закона одного греческого божества, про который в ревью сказано не было

2023-10-17 07:45 UTC, dmgorshenin commented on cash_machine.py
> +        return self.branch_finder
в строчках 11-15 нарушен PEP8: необходимо начинать операторы с новой строки с тем же отступом и использовать скобки

2023-10-17 07:49 UTC, dmgorshenin commented
в классе CashMachine следовало бы убрать метод branch_finder и вместо него написать метод __init__, в котором принимается объект класса BranchFinder 
в методе withdraw разделить return на несколько частей для большей читабельности кода

2023-10-17 08:54 UTC, alxmcs commented on cash_machine.py
> +            .withdraw(amount)
Я все еще не наблюдаю внятного описания проблемы и внятного писания проблемы на этих строках.
Это не РЕР. Хватить вспоминать про РЕР. Про РЕР в ходе ревью вспомнили достаточно.

Попробуем по-другому.  

Этот код нарушает закон Деметры. Почему? Что надо сделать, чтобы он не нарушал?

2023-10-17 11:37 UTC, dmgorshenin commented on cash_machine.py
> +            .withdraw(amount)
объект CashMachine пытается напрямую получить доступ к объекту BranchFinder и так далее к BankAccount, это нарушает закон Деметры, так как объект CashMachine слишком много знает о структуре и внутренних объектах других классов.
можно переделать код таким образом: 
`branch = self.branch_finder.find_branch_for_town(town)
 account = branch.personal_accounts().get_account_for_customer(customer)
 return account.withdraw(amount)`

2023-10-17 11:51 UTC, dmgorshenin commented on cash_machine.py
> +            .withdraw(amount)
объект CashMachine пытается напрямую получить доступ к объекту BranchFinder и так далее к BankAccount, это нарушает закон Деметры, так как объект CashMachine слишком много знает о структуре и внутренних объектах других классов.
можно переделать код таким образом:
`def withdraw(self, town: str, customer: str, amount: Decimal):`
       `branch = self.branch_finder.find_branch_for_town(town)`
       `account = branch.personal_accounts().get_account_for_customer(customer)`
       `return account.withdraw(amount)`

либо ввести дополнительные методы для получения отдельных данных:
`def get_account(self, town: str, customer: str):`
        `branch = self.branch_finder.find_branch_for_town(town)`
        `return branch.personal_accounts().get_account_for_customer(customer)`

    `def withdraw(self, town: str, customer: str, amount: Decimal):`
        `account = self.get_account(town, customer)`
        `return account.withdraw(amount)`

2023-10-17 12:04 UTC, alxmcs reviewed
Зачтено

2023-10-17 12:04 UTC, closed without merging