6313 Панюшкин
itsecd/ptm-2 pull request #10
Opened 2023-10-13 07:17 UTC by alxmcs

Это часть кода дипломного проекта одного из моих студентов, написанная около 3х лет назад.
Без слез на нее взглянуть трудно.
Твоя задача в рамках ревью - описать проблемы (и предложить варианты их решения) в наиболее болезненных для просмотра частях этого кода.

2023-10-13 10:15 UTC, Santas7 commented on fusing.py
> +from tqdm import tqdm
нарушение порядка импортов (сначала идут import потом идут from - соблюдая алфавитный порядок)

2023-10-13 10:21 UTC, Santas7 commented on fusing.py
> +def fusing_gui(files, additional_channel, progress_bar_info):
нет typehints подробности можете смотреть в руководстве PEP. [PEP 484 Type Hints](https://peps.python.org/pep-0484/)

2023-10-13 10:23 UTC, Santas7 commented on fusing.py
> +    import math
В соответствии с PEP 8, инструкции **import** должны располагаться в начале файл. Это помогает лучше организовать код и улучшает его читаемость.

2023-10-13 10:25 UTC, Santas7 commented on fusing.py
> +    progress_bar_info[1].config(text="0")
отсутствуют пробелы вокруг операторов присваивания

2023-10-13 10:27 UTC, Santas7 commented on fusing.py
> +    # error_helper = np.ones((additional_channel[1].shape[0], additional_channel[1].shape[1])) / 1000000000
УБРАТЬ лишний комментарий в этой части кода

2023-10-13 10:28 UTC, Santas7 commented on fusing.py
> +    for m in tqdm(range(0, len(files)), desc="Комплексирование: "):
отсутствуют пробелы вокруг операторов присваивания

2023-10-13 10:28 UTC, Santas7 commented on fusing.py
> +        disp_err = additional_channel[m]# + error_helper
Аналогично (лишний комментарий)

2023-10-13 10:29 UTC, Santas7 commented on fusing.py
> +        progress_bar_info[1].config(text=round(progress_bar_info[0]['value']))
Аналогично (пробелы вокруг оператора присваивания)

2023-10-13 10:34 UTC, Santas7 commented on fusing.py
> +        progress_bar_info[1].config(text=round(progress_bar_info[0]['value']))
Аналогично (добавить пробелы где оператор присваивания)

2023-10-13 10:34 UTC, Santas7 commented on fusing.py
> +    progress_bar_info[1].config(text=progress_bar_info[0]['value'])
Аналогично (добавить пробелы где оператор присваивания)

2023-10-13 10:44 UTC, Santas7 requested changes
Общие замечания по коду:

- неправильное подключение модулей
- нет docstring и typehints в функции
- отсутствуют пробелы где оператор присваивания

2023-10-16 08:10 UTC, alxmcs reviewed
На будущее:
![image](https://github.com/itsecd/ptm-2/assets/70561974/2647df9e-35e1-46e8-b299-112ac4391b21)
Лучше нажимать правую кнопку, чтобы не бомбить мне электронную почту оповещениями.

А само ревью стоит расширить

2023-10-16 08:10 UTC, alxmcs commented on fusing.py
> +            if additional_channel[0][i][j] == 0:
Я бы присмотрелся к коду на 30-33 строках

2023-10-16 08:10 UTC, alxmcs commented on fusing.py
> +                    if flag_nan:
И к очень странному назначению этой переменной

2023-10-16 08:10 UTC, alxmcs commented on fusing.py
> +            if pixel_matrix[i][j] < 0.0000005 or pixel_matrix[i][j] > 255:
К обилию магических чисел в коде

2023-10-16 08:10 UTC, alxmcs commented on fusing.py
> +    a = 0
К сомнительно названным переменным

2023-10-16 08:10 UTC, alxmcs commented on fusing.py
> +def fusing_gui(files, additional_channel, progress_bar_info):
И в целом предложил бы варианты для декомпозиции данной функции, потому что она выполняет две различные задачи - обновляет проперти прогресс бара и занимается комплексированием набора изображений.

2023-10-16 08:54 UTC, Santas7 requested changes

2023-10-16 08:54 UTC, Santas7 commented on fusing.py
> +    a = 0
согласно стандартам **PEP 8** переменные должны именоваться таким образом, чтобы было понятно, что эти переменные делают в данном коде. (в строчках 14-15 можно было бы еще использовать множественное присваивание a, b = 0, 0 но опять же нужно пофиксить или убрать названия переменных)

2023-10-16 08:54 UTC, Santas7 commented on fusing.py
> +            if additional_channel[0][i][j] == 0:
строчки 30-33 можно объединить в один блок if, используя логический оператор ИЛИ (or)

2023-10-16 08:54 UTC, Santas7 commented on fusing.py
> +            if pixel_matrix[i][j] < 0.0000005 or pixel_matrix[i][j] > 255:
вероятно здесь представлены пороговый числа, было бы логичным записать в таком виде условие 0.0000005 <= pixel_matrix[i][j] <= 255

2023-10-16 08:54 UTC, Santas7 commented on fusing.py
> +                    if flag_nan:
переменная flag_nan как по мне является бесполезной в этом куске кода (следует ее удалить), _т.к там идет обнуление в блоке if pixel_matrix, а следом идет моментальное присвоение ей нового значения -> проверка if явл-ся бесполезной!_

2023-10-16 08:54 UTC, Santas7 commented on fusing.py
> +def fusing_gui(files, additional_channel, progress_bar_info):
Проанализировав еще раз предложенный код пришел к выводу на деление изначальной функции на несколько под-функций: например как то так: одну для комплексирования изображений (**fuse_images**), а другую для пост-обработки (**post_process_pixel_matrix**), и вероятно еще обновление прогресс бара (**update_progress_bar**)

2023-10-16 11:42 UTC, alxmcs reviewed
Зачтено

2023-10-16 11:42 UTC, closed without merging