6312 Куспанова
itsecd/ptm-2 pull request #11
Opened 2023-10-13 07:28 UTC by alxmcs

Это часть кода дипломного проекта одного из моих студентов, написанная около 3х лет назад.
Здесь огромное количество code smells. Твоя задача - найти наибольшее их количество и предложить варианты от них избавиться.

2023-10-13 17:46 UTC, d7anSeR requested changes

2023-10-13 17:46 UTC, d7anSeR commented on baseFunctions.py
> +    if (("kitchen" in y1) and ("kitchen" in y2)) and (("mi" in y1) and ("mi" in y2)): dec = 1
думаю стоит текстовые значения записать в переменные до if-блоков для повышения читабельности и понимания кода

2023-10-13 17:46 UTC, d7anSeR commented on baseFunctions.py
> +def define_class(y1, y2):
не хватает тайпхитинга и докстринга

2023-10-13 17:46 UTC, d7anSeR commented on baseFunctions.py
> +    if (("room" in y1) and ("room" in y2)) and (("iphone" in y1) and ("iphone" in y2)): dec = 1
тут аналогично бы объединила бы строчки 31-33 в один if

2023-10-13 17:46 UTC, d7anSeR commented on baseFunctions.py
> +    f1, t1, s1 = spectrogram(x)
я бы переименовала бы переменные для лучшего восприятия кода

2023-10-13 17:46 UTC, d7anSeR commented on baseFunctions.py
> +    return f1, t1, s1
не хватает заключительного пробела в скрипте

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +chi_points = []
непонятное имя переменной

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +umann_points = []
непонятное имя переменной

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +
думаю лишние пробелы стоит убрать

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +
думаю лишние пробелы стоит убрать

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +        [a, b, c] = statistics.use_stat_for_spectr(train_split[i], train_split[j])
думаю стоит переименовать переменные

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +    for j in range(i + 1, len(train_split)):
так как len(train_split) используется несколько раз я бы вынесла его значение в отдельную переменную

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +df = pandas.DataFrame({'chi': chi_points, 'unamm': umann_points, 'stud': student_points, 'pair': labels, 'middle': middles})
думаю стоит исправить либо на "unamm", либо на"umann"

2023-10-13 17:46 UTC, d7anSeR commented on baseFunctions.py
> +def get_data_set(dyrectory):
это не критично, но в слове "dyrectory" ошибка

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +inside_points_umann = []
39-41 можно объединить в одну:  inside_points_chi, inside_points_student, inside_points_umann = [], [], [}

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +predicted = []
43-46 также можно объединить в одну как и было предложено выше

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +all_model = classifier()
48-52 также можно объединить в одну как и было предложено вы

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +all_x_train, all_x_test, all_y_train, all_y_test = train_test_split(all_vec, labels, test_size=0.30)
66-70 строчки - символы "х" и "у" немного затрудняют понимание кода, рекомендую переименовать переменные(например, х_chi_train)

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +
лишние пробелы думаю стоит убрать

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +
лишние пробелы думаю стоит убрать

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +all_model.fit(X=all_x_train, y=all_y_train)
думаю в методе .fit стоит либо явно прописывать(x =.. и y = ...), либо просто писать аргументы в скобках. Не смешивать оба варианта

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +chi_points = np.array(chi_points)
метод reshape можно использовать в той же строчке,  где и создается массив. так код значительно сократится в объеме

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +report_chi = [accuracy_score(chi_y_test, chi_pred), f1_score(chi_y_test, chi_pred), precision_score(chi_y_test, chi_pred), recall_score(chi_y_test, chi_pred)]
длины строчек превышают 79 символов по pep8

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +print("5", report_all)
принты на 91-95 строчках можно объединить в цикл, что значительно упростит понимание кода

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +report_uman = [accuracy_score(umann_y_test, umann_pred), f1_score(umann_y_test, umann_pred), precision_score(umann_y_test, umann_pred), recall_score(umann_y_test, umann_pred)]
длины строчек превышают 79 символов по pep8

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +
лишние пробелы стоит исключить

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +print("5", report_all)
не хватает заключительной пустой строки в скрипте

2023-10-13 17:46 UTC, d7anSeR commented on statisticsClassification.py
> +
85-89 строчки: думаю можно было промежуточные значения записать в список, а потом в цикле передавать значения  в accuracy_score из списка, а результат записывать в новый список. это упростило бы код

2023-10-16 08:17 UTC, alxmcs reviewed
В ревью показана большая часть ошибок в коде, связанная со стандартами кодирования и эффективным использованием конструкция языка. 
Но хотелось бы еще получить предложения по декомпозиции модуля `statisticsClassification.py` - на какие функции/классы стоит разделить сплошное полотно его кода и каким образом эффективнее передавать в них параметры.

2023-10-16 16:29 UTC, d7anSeR requested changes
Ремарки по коду:
- стоит сделать отдельный скрипт-main.py, где бы запускалось: if __name__ == "__main__" и т.д. И сделать так, чтобы этот скрипт запускал непосредственно сам файл statisticsClassification.py (вообще рекомендую переименовать названия скриптов через "_")
- в statisticsClassification.py я бы сделала класс, в котором все необходимые циклы и действия обернула бы в методы, а указанные списки и переменные в поля класса  в виде словариков(это бы значительно упростило бы жизнь....)
- в main.py - я бы сделала отдельные функции, которые обращались бы к необходимым методам класса, сюда же бы вынесла отдельную функцию для df

2023-10-16 16:29 UTC, d7anSeR commented on statisticsClassification.py
> +
для вычисления метрик качества моделей я бы тоже создала отдельный метод, куда просто передавала необходимые значения в переменные, и чтобы метод возвращал полученный список

2023-10-16 16:29 UTC, d7anSeR commented on statisticsClassification.py
> +all_model = classifier()
для классификаторов я бы тоже сделала отдельный словарик, который являлся бы полем класса

2023-10-17 07:26 UTC, closed without merging