6313 Морозов
itsecd/ptm-2 pull request #14
Opened 2023-10-14 06:17 UTC by alxmcs

Этот код на ревью мне прислал один из моих дипломников около года назад. Авторская орфография сохранена.
Код имеет существенное количество проблем, о части которых его автор был в курсе.
В ревью хотелось бы увидеть помимо озвучивания проблем кода, еще и варианты их преодоления.

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +
Отступ не соответсвует пеп8

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +np.save("errors_massive", errors_mas)
лучше обойтись без глобального объявления переменной

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +class Image_formation:
отсутсвует описание класса

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +    def forming(self):
отсутсвует докстринг и тайпхинт

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +        formed_img = Pixel_avg()
лучше обойтись без создания переменной и использовать в return сразу Pixel_avg() вместо  formed_img

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +    def save_img(self):
отсутсвует докстринг и тайпхинт

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +        img = self.forming()
лучше обойтись без создания переменной и использовать в return сразу self.forming()

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +class Deserialize_errors:
Отсутсвует описание класса

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +class Deserialize_npy(Deserialize_errors):
Отсутсвует описание класса

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +    def deserialize(self, file_name):
отсутсвует докстринг и тайпхинт

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +class Deserialize_JSON(Deserialize_errors):
отсутсвует описание класса

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +    def deserialize(self, file_name):
отсутсвует докстринг и тайпхинт

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +class Pixel_formation:
без комментариев лучше такое не оставлять(

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +        return np.load(f"{file_name}.npy")
а вот тут красавчик я бы диплом выдал сразу, все вместе без лишних переменных

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +class Pixel_avg(Pixel_formation):
класс без коментариев написан

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +        """Не знаю как посчитать количество изображений приходящих в модуль, поэтому 5"""
подправить докстринг, сделать тайпихнт

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +            """"""
пустой комментраий

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +        """Извените за говнокод поправлю в ближайшее время(когда найду метод для сложения элементов массивов)"""
покопаться в np массивах

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +    def avg(self,img_name):
докстринг тайпхинт

2023-10-24 18:43 UTC, kingtuler1454 commented on complexing.py
> +    test2 = Deserialize_JSON()
лучше поменять местами взаимодействия с test2 и test, а то путаница

2023-10-27 08:11 UTC, alxmcs reviewed
Ревью было бы неплохо пополнить:
1) Комментарием касательно именований классов
2) Примером кода по превращению части циклов на 50-52 строке в компрехеншен

2023-10-28 06:47 UTC, kingtuler1454 requested changes

2023-10-28 06:47 UTC, kingtuler1454 commented on complexing.py
> +class Deserialize_npy(Deserialize_errors):
стоит объединить с   Deserialize_JSON и переименовать класс  в  просто   Deserialize_errors

2023-10-28 06:47 UTC, kingtuler1454 commented on complexing.py
> +class Image_formation:
Имя класса устраивает но функцию save_img стоит вынести  в отдельный класс   с именем Image_read-write

2023-10-28 06:47 UTC, kingtuler1454 commented on complexing.py
> +    def read_images(self,number_of_images,img_name):
Функцию занести в класс Image_read_write

2023-10-28 11:41 UTC, alxmcs reviewed
Зачтено

2023-10-28 11:41 UTC, closed without merging