6313 Кадников Егор
itsecd/ptm-2 pull request #17
Opened 2023-10-14 06:47 UTC by alxmcs

Это часть кода дипломного проекта одного из моих студентов. Код написан порядка 3 лет назад.
Думаю, его проблемы достаточно очевидны. В ревью хотелось бы увидеть предложения по декомпозиции кода.

2023-11-05 10:56 UTC, acebiscuits requested changes

2023-11-05 10:56 UTC, acebiscuits commented on 05. pyramid - TRANSLATION.py
> +io.imsave(pathOut + files[0], img_as_ubyte(ref_image))  # сохранить первый файл
Для лучшей читабельности кода следует разнести его на логические части и разнести пустыми строками, например:
Часть, относящаяся к обработке времени:
```python
total_time = time.time()
``` 
Часть с обработкой путей:
```python
pathIn = "Test Sequence" 
pathOut = "Test Sequence Out/test5-9 - pystackreg/1. TRANSLATION/" 
if not os.path.exists(pathOut): os.makedirs(pathOut) 
``` 
Часть с первичной обработкой:
```python
files = [f for f in listdir(pathIn) if isfile(join(pathIn, f))] 
ref_image = img_as_ubyte(rgb2gray(io.imread(join(pathIn, files[0]))))  # задаём эталон
io.imsave(pathOut + files[0], img_as_ubyte(ref_image))  # сохранить первый файл
``` 
плюс, можно обойтись без некоторых комментариев

2023-11-05 10:56 UTC, acebiscuits commented on 05. pyramid - TRANSLATION.py
> +    io.imsave(pathOut + files[i], corrected_image)
можно вынести в отдельную функцию

2023-11-05 10:56 UTC, acebiscuits commented on 06. pyramid - RIGID BODY.py
> +io.imsave(pathOut + files[0], img_as_ubyte(ref_image))  # сохранить первый файл
Для лучшей читабельности кода следует разнести его на логические части и разнести пустыми строками, например:
Часть, относящаяся к обработке времени:
```python
total_time = time.time()
``` 
Часть с обработкой путей:
```python
pathIn = "Test Sequence" 
pathOut = "Test Sequence Out/test5-9 - pystackreg/2. RIGID BODY/"
if not os.path.exists(pathOut): os.makedirs(pathOut) 
``` 
Часть с первичной обработкой:
```python
files = [f for f in listdir(pathIn) if isfile(join(pathIn, f))] 
ref_image = img_as_ubyte(rgb2gray(io.imread(join(pathIn, files[0]))))  # задаём эталон
io.imsave(pathOut + files[0], img_as_ubyte(ref_image))  # сохранить первый файл
``` 
плюс, можно обойтись без некоторых комментариев

2023-11-05 10:56 UTC, acebiscuits commented on 05. pyramid - TRANSLATION.py
> +for i in range(1, len(files) - 1):
для читабельности можно отделить пустой строкой

2023-11-05 10:56 UTC, acebiscuits commented on 06. pyramid - RIGID BODY.py
> +for i in range(1, len(files) - 1):
для читабельности можно отделить пустой строкой

2023-11-05 10:56 UTC, acebiscuits commented on 06. pyramid - RIGID BODY.py
> +    io.imsave(pathOut + files[i], corrected_image)
можно вынести в отдельную функцию

2023-11-06 08:09 UTC, alxmcs reviewed
Мне кажется, что добавление пустых строк не сильно помогут в увеличении читаемости данного кода. Думаю, тут стоит предложить декомпозировать код по функциям/классам.

Более того, ты написал по 3 одинаковых (вплоть до строк, к которым они относятся) комментария к 2м файлам с исходным кодом. Это наводит на мысль о том, что код там подозрительно одинаковый. Может быть, исходники можно отрефакторить так, чтобы избавиться от необходимости иметь два практически идентичных скрипта?

2023-11-10 19:21 UTC, acebiscuits requested changes

2023-11-10 19:21 UTC, acebiscuits commented on 05. pyramid - TRANSLATION.py
> +    # -------------Рассчёт СКО----------------#
для декомпозиции и разделения кода на функции данный блок можно вынести в отдельную функцию:
```python
def coordination(pathIn: str, files: list, ref_image, pathOut: str): ->None
global sko
global sko_arr
global time_arr
for i in range(1, len(files) - 1):
    # -------Процесс согласования НАЧАЛО------#
    start_time = time.time()
    offset_image = img_as_ubyte(rgb2gray(io.imread(join(pathIn, files[i]))))
    if sys.argv[1] == 'TRANSLATION':
        reg_instance = StackReg(StackReg.TRANSLATION)
    elif sys.argv[1] == 'RIGID_BODY':
        reg_instance = StackReg(StackReg.RIGID_BODY)
    else:
        pass#some default action
    corrected_image = reg_instance.register_transform(ref_image, offset_image)
    corrected_image = img_as_ubyte(
        (corrected_image - np.min(corrected_image)) / (np.max(corrected_image) - np.min(corrected_image)))
    io.imsave(pathOut + files[i], corrected_image)
    time_arr[i - 1] = time.time() - start_time
    # -------Процесс согласования КОНЕЦ-------#
    print("--- %s seconds ---" % (time.time() - start_time))
    sko_arr[i - 1] = np.sum((corrected_image.astype("float") - ref_image.astype("float")) ** 2)
    sko_arr[i - 1] /= float(ref_image.shape[0] * ref_image.shape[1])
    print("SKO[" + str(i) + "]: " + str(sko_arr[i - 1]) + "\n")
    sko += sko_arr[i - 1]
    # -------------Расчёт СКО----------------#
``` 
плюс к декомпозиции, используя аргументы командной строки, можно прийти к одному универсальному скрипту, вместо двух почти идентичных

2023-11-10 19:21 UTC, acebiscuits commented on 05. pyramid - TRANSLATION.py
> +pathOut = "Test Sequence Out/test5-9 - pystackreg/1. TRANSLATION/"  # куда сохранять файлы
здесь также следует применить аргументы командной строки, сделав скрипт более универсальным:
```Python
if sys.argv[1] == 'TRANSLATION':
    pathOut = f"Test Sequence Out/test5-9 - pystackreg/1. TRANSLATION/"
elif sys.argv[1] == 'RIGID_BODY':
    pathOut = "Test Sequence Out/test5-9 - pystackreg/2. RIGID BODY/"
else:
    pass#some default action
```

2023-11-10 19:21 UTC, acebiscuits commented on 05. pyramid - TRANSLATION.py
> +
необходимо импортировать sys для использования аргументов командной строки

2023-11-11 05:29 UTC, alxmcs reviewed
Использование глобальных переменных явно излишне в задаче, которую решает код.
Но, думаю, зачесть это можно.

2023-11-11 05:30 UTC, closed without merging