6312 Рыженкова
itsecd/ptm-2 pull request #19
Opened 2023-10-14 07:02 UTC by alxmcs

Это часть кода автоматизации экспериментов в дипломном проекте одного из моих студентов. Код написан порядка 3 лет назад.
Думаю, его проблемы достаточно очевидны. В ревью хотелось бы увидеть предложения по декомпозиции кода.

2023-10-16 20:38 UTC, DianaRyz requested changes

2023-10-16 20:38 UTC, DianaRyz commented on 07. pyramid - SCALED ROTATION.py
> +    # -------Процесс согласования НАЧАЛО------#
Убрать комментарии. Для логического разделения можно добавить пустую строку
Здесь и далее по коду

2023-10-16 20:38 UTC, DianaRyz commented on 07. pyramid - SCALED ROTATION.py
> +sko = 0
Добавить пустую строку для логического разделения (первый блок - работа с файлами, второй блок - переменные для СКО и времени)

2023-10-16 20:38 UTC, DianaRyz commented on 08. pyramid - AFFINE.py
> +
Удалить пустую строку

2023-10-16 20:38 UTC, DianaRyz commented on 08. pyramid - AFFINE.py
> +from os.path import isfile, join
Импортируемые файлы должны быть сгруппированы в следующем порядке:

- Импорт стандартной библиотеки.
- Связанный импорт третьими сторонами.
- Импорт для локального приложения / библиотеки.

Между каждой группой импортов должна быть пустая строка

2023-10-16 20:38 UTC, DianaRyz commented on 08. pyramid - AFFINE.py
> +total_time = time.time()
Добавить 2 пустые строки между import и кодом

2023-10-16 20:38 UTC, DianaRyz commented on 08. pyramid - AFFINE.py
> +pathOut = "Test Sequence Out/test5-9 - pystackreg/4. AFFINE/"  # куда сохранять файлы
1. Именование переменных должно быть в едином стиле - в нижнем регистре, со словами, разделенными подчеркиванием
2. Убрать комментарии (здесь и далее по коду)

2023-10-16 20:38 UTC, DianaRyz commented on 08. pyramid - AFFINE.py
> +sko = 0
Пустая строка для логического разделения блоков

2023-10-16 20:38 UTC, DianaRyz commented on 08. pyramid - AFFINE.py
> +    # -------Процесс согласования НАЧАЛО------#
Заменить комментарии на пустую строку для логического разделения блоков (здесь и далее по коду)

2023-10-16 20:38 UTC, DianaRyz commented on 08. pyramid - AFFINE.py
> +        if (i != 50):
Убрать скобки в if

2023-10-16 20:38 UTC, DianaRyz commented on 07. pyramid - SCALED ROTATION.py
> +
Удалить пустую строку

2023-10-17 07:36 UTC, alxmcs reviewed
Было бы неплохо предложить вариант декомпозиции сплошного полотна кода в модулях на классы/функции. 
Возможно, можно отрефакторить этот код так, чтобы не иметь два скрипта с практически идентичным кодом.

2023-10-19 10:57 UTC, DianaRyz requested changes
Отличие двух представленных файлов заключается в `pathOut` и `reg_instance` (StackReg), в остальном код идентичен, поэтому можно объединить эти два файла и создать класс с методами

Параметры объекта класса: `pathOut` и `reg_instance`
Методы: 
- Загрузка изображений
- Эталонное изображение
- Процесс согласования
- Расчет СКО
- Запись в файл

В коде также отсутствует `if __name__ == "__main__"`
В нем нужно создать объект класса и вызывать необходимые методы

2023-10-19 10:57 UTC, DianaRyz commented on 07. pyramid - SCALED ROTATION.py
> +    for i in range(1, len(sko_arr) + 1):
Запись в файл сделать методом

2023-10-19 10:57 UTC, DianaRyz commented on 07. pyramid - SCALED ROTATION.py
> +    print("SKO[" + str(i) + "]: " + str(sko_arr[i - 1]) + "\n")
Расчет СКО сделать методом

2023-10-19 10:57 UTC, DianaRyz commented on 07. pyramid - SCALED ROTATION.py
> +    offset_image = img_as_ubyte(rgb2gray(io.imread(join(pathIn, files[i]))))
Процесс согласования сделать методом

2023-10-19 10:57 UTC, DianaRyz commented on 07. pyramid - SCALED ROTATION.py
> +io.imsave(pathOut + files[0], img_as_ubyte(ref_image))  # сохранить первый файл
Сделать методы загрузки изображений и создания эталона

2023-10-20 09:54 UTC, alxmcs reviewed
Зачтено

2023-10-20 09:54 UTC, closed without merging