6311 Чукарев
itsecd/ptm-2 pull request #2
Opened 2023-10-12 07:45 UTC by alxmcs

Этот классический пример kata для рефакторинга. Несмотря на то, что кода мало, проблем в нем вполне достаточно для объемного ревью.
Напоминаю, что помимо указания на проблемы в коде, я ожидаю и некоторые предложения по их решению.

2023-10-12 18:05 UTC, Mishachuu commented on expense_report.py
> +
нарушение pep8, пропуск строки

2023-10-12 18:11 UTC, Mishachuu commented on expense_report.py
> +
нарушение pep8, пропуск строки

2023-10-12 19:24 UTC, Mishachuu requested changes
следует добавить докстринги и тайпхинты к функции

2023-10-12 19:24 UTC, Mishachuu commented on expense_report.py
> +    DINNER = auto()
нарушение pep8, не правильное названии переменных класса. Так же для удобства можно сделать список

2023-10-12 19:24 UTC, Mishachuu commented on expense_report.py
> +            if expense.type == ExpenseType.DINNER:
для удобства  все эти проверки можно заменить на match case

2023-10-16 07:13 UTC, alxmcs commented on expense_report.py
> +class ExpenseType(Enum):
Я бы предложил присмотреться повнимательнее к этому енаму и к коду на 29-36 строках. Возможно, простое перечисление типов приемов пищи не так сильно полезно в этом коде. Возможно, в него имеет смысл упаковать и некоторую другую информацию.

2023-10-16 18:42 UTC, Mishachuu requested changes

2023-10-16 18:42 UTC, Mishachuu commented on expense_report.py
> +    type: ExpenseType
Для того чтобы снизить цикломатическую сложность других участков кода можно вместо enum описать родительский класс expensive, а от него классы наследники dinner,breakfast ... в полях которых помимо названия, цены можно добавить поле flag, который будет отслеживать преодолен ли  meal_over_expenses_marker

2023-10-17 07:25 UTC, alxmcs reviewed
Зачтено

2023-10-17 07:25 UTC, closed without merging