6311 Куненков
itsecd/ptm-2 pull request #22
Opened 2023-10-15 10:44 UTC by alxmcs

Это часть кода автоматизации экспериментов в дипломном проекте одного из моих студентов. Код написан порядка 3 лет назад.
Думаю, его проблемы достаточно очевидны. В ревью хотелось бы увидеть предложения по декомпозиции кода.

2023-10-15 13:20 UTC, razzzenya requested changes

2023-10-15 13:20 UTC, razzzenya commented on 11. cross correlation - Chi2.py
> +with open(pathOut + 'SKO.txt', 'w') as f:
было бы неплохо использовать os.path.join

2023-10-15 13:20 UTC, razzzenya commented on 11. cross correlation - Chi2.py
> +    # ------------Запись в файл---------------#
Если смотреть в целом то можно было бы разделить весь код на функции(или же методы одного класса) и последовательно вызывать их (вывод я сделал смотря на комментарии от автора), ну и переменные pathIn, pathOut, noise можно было бы загружать как параметры из .json файла. Ну и само собой тогда надобности в таких комментариях уже не будет

2023-10-15 13:20 UTC, razzzenya commented on 11. cross correlation - Chi2.py
> +    io.imsave(pathOut + files[i], corrected_image)
было бы неплохо использовать os.path.join

2023-10-15 13:20 UTC, razzzenya commented on 12. Optical Flow Based Shift.py
> +from os.path import isfile, join
Необходимо отсортировать импорты в алфавитном порядке

2023-10-15 13:20 UTC, razzzenya commented on 12. Optical Flow Based Shift.py
> +pathOut = "Test Sequence Out/test4 - Optical Flow Based Shift/"  # куда сохранять файлы
переменные pathIn и pathOut можно было бы объявить константой

2023-10-15 13:20 UTC, razzzenya commented on 12. Optical Flow Based Shift.py
> +sko = 0
тоже следовало бы поменять имя переменной

2023-10-15 13:20 UTC, razzzenya commented on 12. Optical Flow Based Shift.py
> +sko_arr = [None] * (len(files) - 1)
и здесь

2023-10-15 13:20 UTC, razzzenya commented on 12. Optical Flow Based Shift.py
> +    xoff = np.mean(flow_x)
можно поменять стиль написания на snake_case, то есть сделать имя x_off или x_offset

2023-10-15 13:20 UTC, razzzenya commented on 12. Optical Flow Based Shift.py
> +    yoff = np.mean(flow_y)
так же и с yoff

2023-10-15 13:20 UTC, razzzenya commented on 11. cross correlation - Chi2.py
> +    xoff, yoff, exoff, eyoff = chi2_shift(ref_image, offset_image, noise,
можно поменять стиль написания на snake_case, то есть сделать имя x_off или x_offset

2023-10-15 13:20 UTC, razzzenya commented on 12. Optical Flow Based Shift.py
> +    io.imsave(pathOut + files[i], corrected_image)
можно было бы использовать os.path.join

2023-10-15 13:20 UTC, razzzenya commented on 12. Optical Flow Based Shift.py
> +with open(pathOut + 'SKO.txt', 'w') as f:
можно было бы использовать os.path.join

2023-10-15 13:20 UTC, razzzenya commented on 12. Optical Flow Based Shift.py
> +    # ------------Запись в файл---------------#
Ну и общее замечание всё тоже

2023-10-15 13:25 UTC, razzzenya commented on 11. cross correlation - Chi2.py
> +
тут еще и нарушение PEP8, необходимы две пустые строки

2023-10-15 13:25 UTC, razzzenya commented on 12. Optical Flow Based Shift.py
> +
тут тоже нарушается PEP8

2023-10-15 13:31 UTC, razzzenya commented on 11. cross correlation - Chi2.py
> +                                          return_error=True, upsample_factor='auto')
кавычки нужно привести к единому виду

2023-10-15 13:31 UTC, razzzenya commented on 11. cross correlation - Chi2.py
> +    corrected_image = shift(offset_image, shift=(-yoff, -xoff), mode='constant')
кавычки нужно привести к единому виду

2023-10-15 13:32 UTC, razzzenya commented on 11. cross correlation - Chi2.py
> +with open(pathOut + 'SKO.txt', 'w') as f:
кавычки нужно привести к единому виду

2023-10-15 13:32 UTC, razzzenya commented on 12. Optical Flow Based Shift.py
> +    corrected_image = shift(offset_image, shift=(-yoff, -xoff), mode='constant')
кавычки нужно привести к единому виду

2023-10-15 13:32 UTC, razzzenya commented on 12. Optical Flow Based Shift.py
> +with open(pathOut + 'SKO.txt', 'w') as f:
кавычки нужно привести к единому виду

2023-10-16 08:22 UTC, alxmcs reviewed
В ревью указаны основные проблемы кода в плане стандартов кодирования и декомпозиции. 
Но хотелось бы почитать конкретику касательно последней - какие логические части кода выделить в отдельные функции или методы/что вынести в константы/ какие фрагменты кода оставить для исполнения под `if __name__=="__main__":`(которого тут, кстати, нет). И сколько в итоге после рефакторинга должно остаться модулей с автоматизацией экспериментов?

2023-10-16 09:46 UTC, razzzenya reviewed
Если подытожить , то было бы хорошо объединить оба файла в один, дабы не повторяться.
Можно было бы сделать класс который решает данные задачи, немного поработать над логикой, чтобы потенциальный юзер мог выбрать какой именно вариант он хочет использовать.

2023-10-16 09:46 UTC, razzzenya commented on 11. cross correlation - Chi2.py
> +time_arr = [None] * (len(files) - 1)
было бы целесообразно вот этот блок программы засунуть под  if __name__=="__main__": 
также он практически полностью совпадает со вторым файлом по коду, единственное отличие это значение переменной pathOut. В принципе можно просто сделать как я писал до этого, то есть сделать pathIn и pathOut параметрами загружаемыми из .json файла.
И хорошим решением было бы сделать отдельную функцию для загрузки этих параметров

2023-10-16 09:46 UTC, razzzenya commented on 12. Optical Flow Based Shift.py
> +time_arr = [None] * (len(files) - 1)
Здесь тоже самое что и в первом файле, нет необходимости это делить на два файла

2023-10-16 09:46 UTC, razzzenya commented on 11. cross correlation - Chi2.py
> +    time_arr[i - 1] = time.time() - start_time
вот в этом блоке уже есть значимые отличия, от следующего файла, однако , можно объединить оба файла, а эти два блока раскидать по разным функциям (или методам)

2023-10-16 09:46 UTC, razzzenya commented on 11. cross correlation - Chi2.py
> +    sko += sko_arr[i - 1]
Тут абсолютно одинаковый код, совпадающий с кодом и 2-го файла, нет смысла его дублировать, достаточно будет засунуть его в функцию

2023-10-16 09:46 UTC, razzzenya commented on 11. cross correlation - Chi2.py
> +            f.write("\t%s\t%s\n" % (sko_arr[i - 1], time_arr[i - 1]))
И здесь тоже код дублируется

2023-10-16 09:47 UTC, razzzenya commented on 11. cross correlation - Chi2.py
> +time_arr = [None] * (len(files) - 1)
тут я имел ввиду что до 21-ой строки можно было бы засунуть его, ну а так если же мы делаем класс, то по сути в 
if name=="main": у нас останется только создание объекта класса и вызов его методов

2023-10-16 09:48 UTC, razzzenya commented on 11. cross correlation - Chi2.py
> +            f.write("\t%s\t%s\n" % (sko_arr[i - 1], time_arr[i - 1]))
я не нажал reques changes...

2023-10-16 11:43 UTC, alxmcs reviewed
Зачтено

2023-10-16 11:43 UTC, closed without merging