6311 Замотохина
itsecd/ptm-2 pull request #23
Opened 2023-10-15 10:58 UTC by alxmcs

Это реализация одной из лабораторных по прикладному программированию из давних времен.  Как видно из кода, задачей было считать данные из файла, произвести их валидацию и вывести по ней статистику.
Основные проблемы тут связаны с модулем `Validator.py`. Хотелось бы увидеть в ревью предложения по декомпозиции кода.

2023-10-17 10:37 UTC, ZamotohinaMaria requested changes

2023-10-17 10:37 UTC, ZamotohinaMaria commented on Validator.py
> +
Ненужная строчка-разделитель, которую можно убрать

2023-10-17 10:37 UTC, ZamotohinaMaria commented on Validator.py
> +
Ненужная строчка-разделитель, которую можно убрать

2023-10-17 10:37 UTC, ZamotohinaMaria commented on Validator.py
> +
Ненужная строчка-разделитель, которую можно убрать

2023-10-17 10:37 UTC, ZamotohinaMaria commented on Validator.py
> +
Ненужная строчка-разделитель, которую можно убрать

2023-10-17 10:37 UTC, ZamotohinaMaria commented on Validator.py
> +
Ненужная строчка-разделитель, которую можно убрать

2023-10-17 10:37 UTC, ZamotohinaMaria commented on Validator.py
> +
Ненужная строчка-разделитель, которую можно убрать

2023-10-17 10:37 UTC, ZamotohinaMaria commented on Validator.py
> +            self.entries.append(i.copy())
инициализацию массива записей можно вынести в отдельный метод

2023-10-17 10:37 UTC, ZamotohinaMaria commented on Validator.py
> +        legal_entries: list[Entry] = []
определение списка можно вывести в функцию init, а сам список сделать элементом класса

2023-10-17 10:37 UTC, ZamotohinaMaria commented on Validator.py
> +        return len(str(passport)) == 6
В классе Entry номер паспорта определен как строка, а не число, поэтому данная проверка на корректность паспортного номера недействительна

2023-10-17 10:37 UTC, ZamotohinaMaria commented on Validator.py
> +        return True
ненужный return, который никогда не вызовется, потому что функция в любом случае вернет значение в блоке try/expect

2023-10-17 10:37 UTC, ZamotohinaMaria commented on Validator.py
> +            return 2.2 > float_height > 1.2
return необходимо вытащить за пределы блока try/except, потому что при возникновении ошибки возврат значения будет неверным

2023-10-17 10:37 UTC, ZamotohinaMaria commented on Validator.py
> +            illegal_keys.append('worldview')
каскад проверок можно сделать более читабельным, добавив пустые строки между условиями

2023-10-17 12:33 UTC, alxmcs reviewed
К ремаркам касательно стандартов кодирования у меня вопросов нет, но было бы неплохо дополнить ревью оценкой качества декомпозиции кода и, возможно, предложить путь его рефакторинга

2023-10-17 12:33 UTC, alxmcs commented on Validator.py
> +            illegal_keys.append('worldview')
В модуле есть куча подозрительно похожих друг на друга (как славянские братья в песнях группы "Коловрат") функций, которые работают по одинаковому сценарию:

* взять строковое значение из яче1йки документа
* заматчить по нему регулярное выражение
* выдать булевый результат матча

(с небольшими вариациями для целочисленных значений, обработку которых можно легко свести к такой же процедуре)

Я подозреваю, что подобные проверки можно генерализовать и ограничиться вызовом единственного метода.
А еще у меня есть ощущение, что можно в каком-нибудь классе попробовать хранить соответствия между заголовком столбца и регексом для его валиации. Таким образом можно было бы заметно сократить код, просто запустив этот метод по всем строкам и столбцам считанного документа вместо этой жуткой кишки из elifов. 

У тебя не появлялось похожих мыслей при анализе этого кода?

2023-10-17 15:53 UTC, ZamotohinaMaria commented
Мыли о том, что нужно убрать этот каскад из elif-ов были, но я не знала, как его можно было бы изменить, поэтому и не стала его писать... про однотипные функции как то не подумалось

2023-10-18 10:01 UTC, alxmcs commented
Тогда давай ты добавишь в ревью чуть более конкретизированное и развернутое описание идеи генерализации валидации данных и я зачту лабу

2023-10-18 10:34 UTC, ZamotohinaMaria commented
хорошо

2023-10-18 10:54 UTC, ZamotohinaMaria requested changes

2023-10-18 10:54 UTC, ZamotohinaMaria commented on Validator.py
> +            illegal_keys.append('worldview')
чтобы убрать сравнение по всем элементам, можно в класс Entry добавить регулярное выражение для проверки элемента. Тогда, функцию сравнения можно сделать универсальной. Например

```
def check_entry(entry):
     if re.match(pattern[key], entry[key]):
            return entry.kye
````
а функцию parse_entry переделать так: 

```
def parse_entry(self, entry: Entry) -> list[str]:
        """Parse simple node"""
        illegal_keys = []

        illegal_keys.append(check_entry(entry))`
````

2023-10-18 11:03 UTC, alxmcs reviewed
Зачтено

2023-10-18 11:03 UTC, closed without merging