6313 Вольгов
itsecd/ptm-2 pull request #24
Opened 2023-10-17 07:20 UTC by alxmcs

Это пример классической kata, где нарушается закон Деметры. Соответственно, надо указать на факт нарушения и предложить свой вариант декомпозиции методов/классов.

2023-11-06 14:03 UTC, the80hz requested changes
Код, который вы написали, не просто требует улучшений — он требует пересмотра с основами ООП в уме.
При ревью представленного кода становится ясно, что основные принципы проектирования и чистоты кода были упущены из виду. Особенно заметны нарушения Закона Деметры, которые приводят к излишней связанности между классами, что является признаком недостаточно продуманной архитектуры.

2023-11-06 14:03 UTC, the80hz commented on Player.py
> +class Player(Target):
Docstrings

2023-11-06 14:03 UTC, the80hz commented on Stats.py
> +class Stats:
Docstrings

2023-11-06 14:03 UTC, the80hz commented on Target.py
> +class SimpleEnemy(Target):
Docstrings

2023-11-07 07:43 UTC, alxmcs reviewed
Зачтено

2023-11-07 07:43 UTC, closed without merging