6313 Елагин
itsecd/ptm-2 pull request #25
Opened 2023-10-18 11:46 UTC by alxmcs

Это код по 3 лабе ОИБ прямиком из мезозоя.
Основная проблема этого кода достаточно очевидна. В ревью (помимо замечаний к оформлению) хотелось бы увидеть предложения по декомпозиции данного кода. Возможно, модулей и функций должно быть заметно больше, чем сейчас.

2023-11-10 09:33 UTC, Donistr requested changes

2023-11-10 09:33 UTC, Donistr commented on main.py
> +from tqdm.notebook import tqdm_notebook
неиспользованный импорт

2023-11-10 09:33 UTC, Donistr commented on main.py
> +def key_generation(symmetric_key_path: str, public_key_path: str, secret_key_path: str) -> None:
я думаю, что функция генерации должна генерировать ключи и возвращать их, а не генерировать и записывать в файлы.
можно разделить эту функцию на две - для генерации ключа симметричного шифрования и ключей ассиметричного шифрования.
я бы назвал эту функцию generate_keys.

2023-11-10 09:33 UTC, Donistr commented on main.py
> +def encrypt_data(initial_file_path: str, secret_key_path: str, symmetric_key_path: str,
я думаю, что эта функция должна принимать на вход уже расшифрованный ключ симметричного шифрования и текст, который нужно зашифровать, а возвращать зашифрованный текст.

2023-11-10 09:33 UTC, Donistr commented on main.py
> +        public_pem = public_key_path + '\\key.pem'
захардкоженное имя файла

2023-11-10 09:33 UTC, Donistr commented on main.py
> +        private_pem = secret_key_path + '\\key.pem'
захардкоженное имя файла

2023-11-10 09:33 UTC, Donistr commented on main.py
> +        symmetric_file = symmetric_key_path + '\\key.txt'
захардкоженное имя файла

2023-11-10 09:33 UTC, Donistr commented on main.py
> +    private_pem = secret_key_path + '\\key.pem'
захардкоженное имя файла

2023-11-10 09:33 UTC, Donistr commented on main.py
> +    symmetric_file = symmetric_key_path + '\\key.txt'
захардкоженное имя файла

2023-11-10 09:33 UTC, Donistr commented on main.py
> +    initial_file = initial_file_path + '\\text.txt'
захардкоженное имя файла

2023-11-10 09:33 UTC, Donistr commented on main.py
> +    encrypted_file = encrypted_file_path + '\\file.yaml'
захардкоженное имя файла

2023-11-10 09:33 UTC, Donistr commented on main.py
> +    dict_t = {'text': c_text, 'iv': iv}
вместо создания словаря можно дописать iv к началу зашифрованного текста

2023-11-10 09:33 UTC, Donistr commented on main.py
> +    symmetric_file = symmetric_key_path + '\\key.txt'
захардкоженное имя файла

2023-11-10 09:33 UTC, Donistr commented on main.py
> +    private_pem = secret_key_path + '\\key.pem'
захардкоженное имя файла

2023-11-10 09:33 UTC, Donistr commented on main.py
> +    encrypted_file = encrypted_file_path + '\\file.yaml'
захардкоженное имя файла

2023-11-10 09:33 UTC, Donistr commented on main.py
> +    decrypted_file = decrypted_file_path + '\\file.txt'
захардкоженное имя файла

2023-11-10 09:33 UTC, Donistr commented on main.py
> +def decrypting_data(encrypted_file_path: str, secret_key_path: str, symmetric_key_path: str,
я думаю, что эта функция должна принимать на вход уже расшифрованный ключ симметричного шифрования и текст, который нужно расшифровать, а возвращать расшифрованный текст.
функция должна называться decrypt_data, по аналогии с encrypt_data

2023-11-10 09:33 UTC, Donistr commented on main.py
> +        prograssbar.update(100)
нет пустой строки в конце файла

2023-11-10 09:33 UTC, Donistr commented on main.py
в каждой функции куча комментариев на каждое действие - большую часть, а то и все можно убрать.
незначащие пустые строки там же где комментарии в функциях - не соответствует pep.
очевидно код нужно разбить на блоки, а не писать всё в одном файле, я бы предложил такие блоки: генерация ключей шифрования, шифрование/расшифровывание данных, чтение/запись файлов и main

2023-11-11 05:35 UTC, alxmcs reviewed
Зачтено

2023-11-11 05:35 UTC, closed without merging