6311 Чумаков
itsecd/ptm-2 pull request #26
Opened 2023-10-18 11:51 UTC by alxmcs

Это код по 3 лабе ОИБ прямиком из мезозоя.
Проблем в этом коде полно. В ревью (помимо замечаний к оформлению) хотелось бы увидеть предложения по декомпозиции данного кода. Возможно все-таки стоит выделить какие-то классы/функции/модули из этого полотнища кода.

2023-10-18 16:51 UTC, mestromezer requested changes
Слова излишни

2023-10-18 16:51 UTC, mestromezer commented on main.py
> +
Не определена точка входа в программу

2023-10-18 16:51 UTC, mestromezer commented on main.py
> +with open('settings.json') as _file:
Можно было бы возникнуть, что _underscore_variable_names это что-то на древнем, а мы в питоне, однако тут и смысл приватного члена теряется, объекта то нет.....

2023-10-18 16:51 UTC, mestromezer commented on main.py
> +if args.generation is not None:
Этот кейс вытягиваем в класс Generator(IEncryptionStrategy). Для Generator переопределяем метод самой собственно работы. 
Вызываем все это дело в Encryption.мето_запуска_работы(){IEncryptionStrategy.algorithm()}

2023-10-18 16:51 UTC, mestromezer commented on main.py
> +parser = argparse.ArgumentParser()
Описать IEncryptionStategy и какой-то context типо Encrytor - будет объектом основного функционала с членом IEncryptionStategy, засунуть в Encrytor этот выбор стратегии в отдельный метод (можно в общем то и в конструктор). 
Таким образом: var = Encrytor(args) => объект Encrytor c полем IEncryptionStategy который является апкастом от одного из трех классов, которые будут содержать алгоритм работы по выбору.
Метод алгоритма декларируем в IEncryptionStategy  и переопределяем для каждого наследника

2023-10-18 16:51 UTC, mestromezer commented on main.py
> +    with open(json_data['symmetric_key'], "wb") as _file:
Естественно все этапы работы выносим в отдельные функции (SingleResponsabilityOLID)

2023-10-18 16:51 UTC, mestromezer commented on main.py
> +elif args.encryption is not None:
Вытягиваем в еще один Encryption(IEncryptionStrategy)

2023-10-18 16:51 UTC, mestromezer commented on main.py
> +    with open(json_data['symmetric_key'], 'rb') as symmetric_file:
Эту всю гадость по прежнему декомпозируем

2023-10-18 16:51 UTC, mestromezer commented on main.py
> +else:
Последняя стратегия, название выбираем по вкусу, так же наследуемся от нашей абстракции поведения

2023-10-18 16:51 UTC, mestromezer commented on main.py
> +    print('Текст расшифрован и сохранен в файл decrypted_file.txt')
Вероятно решение с Strategy далеко не лучшее так как генерируется туча повторяющегося кода. Разумнее было бы просто тупо декомпозировать все это дело в огромный класс с кучей методов и использовать это дело еще куда большей тучей вызовов и постоянной перестановкой аргументов. А может такой вариант и не лучше. Я бы на питоне лучше вообще ничего не писал

2023-10-18 16:51 UTC, mestromezer commented on main.py
> +    from cryptography.hazmat.primitives import padding
Так это что такое 0_о

2023-10-18 16:51 UTC, mestromezer commented on main.py
> +        key_size=2048
Магические числа (можно сделать константами класса или хранить в кофигах)

2023-10-18 16:51 UTC, mestromezer commented on main.py
> +    dcs_key = d_private_key.decrypt(cim_symmetric_key, padding.OAEP(mgf=padding.MGF1(algorithm=hashes.SHA256()),
не могу читать такие большие строки

2023-10-18 16:51 UTC, mestromezer commented on main.py
> +    print(private_key)
спасибо, очень приятно, но лучше сразу на reddit запостить вдруг кому-то понадобятся шифруемые данные

2023-10-19 08:08 UTC, alxmcs reviewed
Зачтено

2023-10-19 08:08 UTC, closed without merging