6311 Шикунов
itsecd/ptm-2 pull request #28
Opened 2023-10-19 10:38 UTC by alxmcs

Это фрагмент кода из 2 лабораторной по прикладному программированию из прошлых лет. В ревью хотелось бы увидеть указание на проблемы кода и варианты их решения

2023-10-19 19:22 UTC, artyEZ requested changes
По моему мнению следует сделать следующее, чтобы привести этот код к виду получшеу

- в одном у нас 2 функции, в другом - функция, повтораяющая действия `copy_to_new_directory`, внутри имеющая генератор рандомной строки
- реализацию всего задания можно вынести в один скрипт, главное - соблюдать `Single Responsibility Principle` для каждой функции, а то понапичкано в каждой по несколько, что не сразу глазу понятно даже с docstring 
- и, конечно же, добавить `if __name__ == "__main__"`, в котором уже последует вывод, как я понимаю, действия двух функций

2023-10-19 19:22 UTC, artyEZ commented on copy_tool.py
> +            file.close()
с 18 по 23 строку код используется не только в данном участке кода, соответственно, выделяем их в 2 функции, чтоб соблюсти Single Responsibility Principle

```
def read_file_content(file_path: str) -> str:
    with codecs.open(file_path, "r", "utf-8") as file:
        return file.read()


def write_file_content(file_path: str, content: str) -> None:
    with codecs.open(file_path, "w", "utf-8") as file:
        file.write(content)

```

2023-10-19 19:22 UTC, artyEZ commented on random_copy_tool.py
> +                    f.close()
Участок кода точь в точь, что и в первом скрипте. Что с ним делать, прописано там же.

2023-10-19 19:22 UTC, artyEZ commented on random_copy_tool.py
> +                    new_name = str(randint(0, 9999)).zfill(4)
Для соблюдения Single Responsibility Principle можем вынести это в функцию:

```
def random_name() -> str:
    return str(randint(0, 9999)).zfill(4)
```

2023-10-20 12:07 UTC, alxmcs reviewed
Отличные предложения по декомпозиции кода.
Хочется еще узнать мнение по некоторым решениям в коде.

2023-10-20 12:07 UTC, alxmcs commented on copy_tool.py
> +            file.close()
Типа такого

2023-10-20 12:07 UTC, alxmcs commented on copy_tool.py
> +            number = path[-8] + path[-7] + path[-6] + path[-5]
Или вот такого

2023-10-20 12:07 UTC, alxmcs commented on copy_tool.py
> +            file = codecs.open(u'' + path_new + "/" + rev_type + "_" + number + ".txt", "w", "utf-8")
И вот такого

2023-10-20 12:32 UTC, artyEZ requested changes

2023-10-20 12:32 UTC, artyEZ commented on copy_tool.py
> +            file = codecs.open(u'' + path_new + "/" + rev_type + "_" + number + ".txt", "w", "utf-8")
Будем использовать функцию `os.path.join` для создания пути к файлу, чтобы избежать пробем  в файловых системах разных ОС:

```
file_path = os.path.join(path_new, f"{rev_type}_{number}.txt")
with codecs.open(file_path, "w", "utf-8") as file:
    file.write(content)
```

2023-10-20 12:32 UTC, artyEZ commented on copy_tool.py
> +            number = path[-8] + path[-7] + path[-6] + path[-5]
Если тут проблема заключается в сложности условий, то можно попробовать решить это с помощью `glob`, сам ранее подобным не пользовался

```
from glob import glob

for filename in glob(os.path.join(path_old, '*.txt')):
    path = os.path.join(path_old, filename)
```

Что здесь делать с магическими числами внутри `path[]`, одному автору известно, надеюсь...

2023-10-20 12:32 UTC, artyEZ commented on copy_tool.py
> +            file.close()
Лучше использовать конструкцию `with` для автоматического закрытия файла после его использования:

```
with codecs.open(u'' + path, "r", "utf-8") as file:
    content = file.read()
```

2023-10-20 13:46 UTC, alxmcs commented on copy_tool.py
> +            number = path[-8] + path[-7] + path[-6] + path[-5]
Это было скорее к тому, что магические элементы имени файла можно было получить слайсингом

2023-10-20 13:48 UTC, closed without merging