initial
itsecd/ptm-2 pull request #29
Opened 2023-10-21 07:11 UTC by alxmcs

Это классическая kata для рефакторинга. В ревью хотелось бы почитать про то, какой code smell тут присутствует, а также как отрефакторить код так, чтобы от него избавиться.

2023-10-21 19:50 UTC, kseniaDubova requested changes
Рефакторинг кода

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                                item.quality = item.quality + 1
Снизить циклическую сложность

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                        item.quality = item.quality + 1
Аналогично

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                        item.quality = item.quality - 1
Преобразовать в декремент 
```ruby
item.quality -= 1
```

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                    item.quality = item.quality + 1
Аналогично преобразовать в инкремент

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                                item.quality = item.quality + 1
Аналогично

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                                item.quality = item.quality + 1
Аналогично

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                item.sell_in = item.sell_in - 1
Аналогично

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                                item.quality = item.quality - 1
Аналогично

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                        item.quality = item.quality + 1
Аналогично

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                if item.quality < 50:
Вынести "магическое число" как const

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                            if item.quality < 50:
Аналогично

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                        if item.sell_in < 6:
Аналогично

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                            if item.quality < 50:
Аналогично

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                    if item.quality < 50:
Аналогично

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                        if item.sell_in < 11:
Аналогично

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +                            if item.quality < 50:
Аналогично

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +    def __init__(self, items):
Добавить type hint

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +    def update_quality(self):
type hint

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +    def __init__(self, name, sell_in, quality):
Аналогично

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +    def __repr__(self):
Аналогично

2023-10-21 19:50 UTC, kseniaDubova commented on gilded_rose.py
> +        return "%s, %s, %s" % (self.name, self.sell_in, self.quality)
Заменить 
```ruby
return f"{self.name}, {self.sell_in}, {self.quality}"
```

2023-10-27 08:14 UTC, alxmcs commented on gilded_rose.py
> +                                item.quality = item.quality + 1
Как?

2023-10-27 08:15 UTC, alxmcs commented on gilded_rose.py
> +                        item.quality = item.quality + 1
Аналогично - каким образом?
Было бы неплохо указать на избыточность некоторых проверок, привести пример кода и т.д.

2023-10-27 08:17 UTC, alxmcs reviewed
Количество "аналогично", которое ты написала в ревью, должно было подтолкнуть тебя к тому, что в коде присутствует некоторая глобальная алгоритмическая проблема, пути к решению которой надо бы написать

2023-10-29 12:30 UTC, kseniaDubova requested changes
Вложенные условия понижают читабельность кода

2023-10-29 12:30 UTC, kseniaDubova commented on gilded_rose.py
> +                                item.quality = item.quality + 1
Вынести в отдельную функцию (эта проверка повторяется 2 раза) 
```rudy
                if item.quality > 0:
                    if item.name != "Sulfuras, Hand of Ragnaros":
                        item.quality = item.quality - 1
```
Эта проверка выполняется 4 раза
```rudy
                  if item.quality < 50:
                      item.quality = item.quality + 1
```
так же два блока if (10-23 и 26-36) в функции update_quality имеют одинаковые сравнения с отличием в одном из else, можно вынести блок в отдельную функцию, а в параметрах передавать ссылку на функцию для этого "несовпадающего" else или иначе

2023-10-30 09:39 UTC, alxmcs reviewed
Зачтено

2023-10-30 09:39 UTC, closed without merging