6311 Гусарова
itsecd/ptm-2 pull request #32
Opened 2023-10-23 14:29 UTC by alxmcs

Это часть кода автоматизации экспериментов в дипломном проекте одного из моих студентов. Код написан порядка 3 лет назад.
В ревью хотелось бы увидеть предложения по декомпозиции и рефакторингу кода.

2023-11-02 10:38 UTC, MaargoGysarova requested changes
Рефакторинг кода

2023-11-02 10:38 UTC, MaargoGysarova commented on 09. pyramid - BILINEAR.py
> +    # -------Процесс согласования НАЧАЛО------#
В цикле for i in range(1, len(files) - 1): индексация начинается с 1 и заканчивается на len(files) - 2, что может привести к ошибке, так как последний элемент списка не будет обработан.
Решение: Измените диапазон цикла на for i in range(1, len(files)):, чтобы обработать все файлы.

2023-11-02 10:38 UTC, MaargoGysarova commented on 09. pyramid - BILINEAR.py
> +        if (i != 50):
В коде есть магические числа, такие как 50, которые не имеют явного значения и могут вызвать недопонимание.
Решение: Замените магические числа на понятные константы или переменные с описательными именами.
MAX_ITERATIONS = 50

2023-11-02 10:38 UTC, MaargoGysarova commented on 09. pyramid - BILINEAR.py
> +sko_arr = [None] * (len(files) - 1)
Имена переменных, такие как sko, sko_arr, и sko_sum, не являются информативными. Это усложняет понимание кода. Рекомендуется использовать более описательные имена переменных, чтобы облегчить чтение и понимание кода.

2023-11-02 10:38 UTC, MaargoGysarova commented on 09. pyramid - BILINEAR.py
> +time_arr = [None] * (len(files) - 1)
Ненужная инициализация массивов: Инициализация массивов sko_arr и time_arr с None и последующее заполнение их данными усложняет код. Можно избежать этого, начиная с пустых списков.

2023-11-02 10:38 UTC, MaargoGysarova commented on 09. pyramid - BILINEAR.py
> +
Разделение кода на функции: Разделите код на функции, каждая из которых будет выполнять конкретную задачу, что улучшит его структуру и читаемость.

2023-11-02 10:38 UTC, MaargoGysarova commented on 09. pyramid - BILINEAR.py
> +        if (i != 50):
Ненадежная проверка условия: Проверка (i != 50) в цикле не имеет смысла, так как i изменяется в пределах диапазона 1 до len(files) - 1. Лучше использовать использовать (i != len(files) - 1).

2023-11-02 10:38 UTC, MaargoGysarova commented on 09. pyramid - BILINEAR.py
> +time_arr = [None] * (len(files) - 1)
sko_sum = 0
sko_arr = []
time_arr = []

2023-11-02 10:38 UTC, MaargoGysarova commented on 09. pyramid - BILINEAR.py
> +    sko += sko_arr[i - 1]
Ненужная переменная sko и sko_arr
Вы используете переменную sko и список sko_arr, чтобы хранить среднеквадратичное отклонение (СКО) и СКО для каждой итерации. Это занимает лишнюю память и не является необходимым.
Используйте sko_sum = 0
sko_sum = 0
sko_i = np.sum((corrected_image.astype("float") - ref_image.astype("float")) ** 2)
sko_i /= float(ref_image.shape[0] * ref_image.shape[1])
sko_sum += sko_i
print("SKO[" + str(i) + "]: " + str(sko_i) + "\n")

average_sko = sko_sum / (len(files) - 1)
print("Average SKO: " + str(average_sko))

2023-11-02 10:58 UTC, alxmcs commented on 09. pyramid - BILINEAR.py
> +
Как насчет привести список потенциальных функций, на который этот код можно декомпозировать?
Сколько в итоге должно остаться модулей с кодом?

2023-11-03 12:56 UTC, MaargoGysarova requested changes

2023-11-03 12:56 UTC, MaargoGysarova commented on 09. pyramid - BILINEAR.py
> +
Как вариант можно декомпозировать так : 
def load_images(path):
    return [io.imread(join(path, f)) for f in listdir(path) if isfile(join(path, f))]

def create_directory_if_not_exists(path):
    if not os.path.exists(path):
        os.makedirs(path)

def save_image(image, path):
    io.imsave(path, img_as_ubyte(image))

def main():
весь оставшиеся код

if __name__ == "__main__":
    main()

2023-11-03 12:56 UTC, MaargoGysarova commented on 09. pyramid - BILINEAR.py
> +
модули load_images, create_directory_if_not_exists, save_image могут быть размещены в отдельных файлах (например, image_utils.py) и импортированы в основном модуле.

2023-11-03 13:02 UTC, alxmcs commented on 10. cross correlation - Cross Correlation Shifts.py
А с этим кодом что делать? Все комментарии в ревью написаны в другом иcходнике

2023-11-03 13:14 UTC, MaargoGysarova commented on 10. cross correlation - Cross Correlation Shifts.py
Так то практически идентичный за исключением пару названий и строк

2023-11-03 15:46 UTC, MaargoGysarova requested changes

2023-11-03 15:46 UTC, MaargoGysarova commented on 10. cross correlation - Cross Correlation Shifts.py
Есть такая идея одинаковые участки кода в двух кодах объединить в единичные модули
Разница в двух кодах - это начало согласования 
все остальное можно вытащить в паттерны 
calk_sko(sko), write_fille(sko, time_arr), 
Два кода объединяем и в зависимости от параметров путей: pathIn, pathOut - он выполняет различные задачи

2023-11-06 07:51 UTC, alxmcs commented on 10. cross correlation - Cross Correlation Shifts.py
В интернете есть картинка с визуализацией инсульта - образы знакомые, но в опознаваемые объекты они не складываются.
<img src="https://github.com/itsecd/ptm-2/assets/70561974/00a4f677-67b7-4a78-953c-e9130c150604" width=200/>
С последним комментарием  примерно такая же ситуация.

Фраза `одинаковые участки кода в двух кодах объединить в единичные модули` ставит меня в ступор. Какие участки, кто такие эти два кода, как выглядит единичный модуль - для меня загадка. 

Как объять разумом одного человека фразу `все остальное можно вытащить в паттерны из функции main() для улучшения понятия кода`, я тоже не понимаю. Классических паттернов проектирования (из книжки, где о них впервые зашла речь) 23 штуки, частных их вариаций - бесконечное количество. Когда я завел речь о паттернах в предыдущем ревью, я ожидал некоторой конкретики касательно их выбора. Какие паттерны подразумеваются для использования тут?

`Два кода объединяем и в зависимости от параметров путей: pathIn, pathOut - он выполняет различные задачи` - звучит тоже крайне сомнительно. Если код выполняет различные задачи в зависимости от значения параметра - значит он нарушает SRP.

В общем, мне бы хотелось некоторых разъяснений.

2023-11-06 10:28 UTC, MaargoGysarova commented on 10. cross correlation - Cross Correlation Shifts.py
Я уже сама не понимаю, что от меня требуется. Я сделала ревью BILINEAR.py, Cross Corelation.py я вообще не стала трогать, потому что мне он показался идентичный первому. В итоге вы просите меня изменить второй, но там разница в пару строк, то есть там те же комментарии к ревью. Я разделила на функции и вынесла их в модули. Что мне нужно?

2023-11-06 10:35 UTC, MaargoGysarova commented on 10. cross correlation - Cross Correlation Shifts.py
Для моего кода, который выполняет обработку изображений и вычисляет среднеквадратичное отклонение (СКО) между эталонным изображением и другими изображениями, можно использовать паттерн Strategy pattern. Паттерн Стратегия позволяет выбирать алгоритм обработки или поведение в зависимости от контекста, не изменяя сам контекст. Например  для определения метода вычисления СКО и метода обработки изображений.

2023-11-06 10:36 UTC, MaargoGysarova commented on 09. pyramid - BILINEAR.py
> +
Для моего кода, который выполняет обработку изображений и вычисляет среднеквадратичное отклонение (СКО) между эталонным изображением и другими изображениями, можно использовать паттерн Strategy pattern. Паттерн Стратегия позволяет выбирать алгоритм обработки или поведение в зависимости от контекста, не изменяя сам контекст. Например для определения метода вычисления СКО и метода обработки изображений.

2023-11-07 07:45 UTC, alxmcs reviewed
Зачтено

2023-11-07 07:45 UTC, closed without merging