6313 Уваров
itsecd/ptm-2 pull request #37
Opened 2023-11-06 08:20 UTC by alxmcs

Это реализация одной из старых лабораторных по прикладному программированию (которая чем-то может напоминать 3 лабораторную по этому предмету, но это не более, чем совпадение). Код здесь декомпозирован далеко не самым удачным образом. В ревью хотелось бы увидеть предложения касательно того, как унифицировать проверки и сократить объем кода.

2023-11-09 13:54 UTC, Rifinn-crypto commented on FileReader.py
> +import Entry
Убрать строку import Entry. Вместо этого, перенести класс Entry в тот же файл, где находится класс FileReader. Таким образом, появится возможность обращаться к классу Entry напрямую из FileReader.

2023-11-09 13:54 UTC, Rifinn-crypto commented on Entry.py
> +    address: str
Убрать строку address: str. Это поле уже задекларировано ранее.

2023-11-09 13:54 UTC, Rifinn-crypto commented on Entry.py
> +    """Node interface"""
Убрать комментарий """Node interface""". В Python принято использовать Docstrings для комментариев к классам и функциям.

2023-11-09 13:54 UTC, Rifinn-crypto commented on FileReader.py
> +    """Reads file data by path name"""
Убрать комментарий, использовать докстринги

2023-11-09 13:54 UTC, Rifinn-crypto commented on FileReader.py
> +import json
Убрать import json. Модуль json уже встроен в язык Python.

2023-11-09 13:54 UTC, Rifinn-crypto commented on FileReader.py
> +    def getData(self) -> list[Entry]:
Привести к PEP8 здесь и далее по коду (не должно быть заглавных букв в названиях функций)

2023-11-09 13:54 UTC, Rifinn-crypto commented on FileReader.py
> +        return self.data
Использовать return self.data.copy() вместо return self.data. Это предотвратит изменение данных из вне.

2023-11-09 13:54 UTC, Rifinn-crypto commented on FileReader.py
> +    """Reads file data by path name"""
здесь и далее по коду

2023-11-09 13:54 UTC, Rifinn-crypto commented on Validator.py
> +import re
Убрать import re. Модуль re уже встроен в язык Python.

2023-11-09 13:54 UTC, Rifinn-crypto commented on Entry.py
Имена файлов не должны иметь заглавных букв

2023-11-09 13:54 UTC, Rifinn-crypto commented on Validator.py
> +class Validator:
Создать отдельный метод check_field для проверки каждого поля в классе. В этом методе ты можешь использовать регулярные выражения для проверки сложных условий (например, для проверки номера телефона).

2023-11-09 13:54 UTC, Rifinn-crypto commented on Validator.py
> +        self.entries = []
Вместо инициализации пустого списка self.entries и последующего добавления элементов из входного списка в цикле, можно использовать генератор списков: self.entries = [entry.copy() for entry in entries].

2023-11-09 13:54 UTC, Rifinn-crypto commented on Validator.py
> +
Привести код в соответствии с PEP8 ( убрать лишние строки здесь и далее по коду)

2023-11-09 14:00 UTC, Rifinn-crypto commented on Validator.py
> +        legal_entries: list[Entry] = []
Использовать генераторы списков для сокращения кода:
   Вместо явного создания пустого списка legal_entries и последующего добавления в него допустимых записей, можно использовать генератор списка для фильтрации записей, соответствующих условию (len(illkeys) == 0).

2023-11-09 14:08 UTC, Rifinn-crypto requested changes

2023-11-09 14:08 UTC, Rifinn-crypto commented on Validator.py
> +        illegal_entries = {
Использовать словари для хранения информации о недопустимых записях:
   Вместо явного перечисления полей в словаре illegal_entries, можно использовать список полей entries и инициализировать словарь с нулевыми значениями для каждого поля. Это позволит автоматически расширять словарь при добавлении новых полей в entries.

2023-11-09 14:08 UTC, Rifinn-crypto commented on Validator.py
> +    def parse_entry(self, entry: Entry) -> list[str]:
Использование методов check_field в методе parse_entry:
   Вместо явного вызова каждого метода проверки поля в методе parse_entry, можно использовать цикл для обхода всех полей записи и вызывать метод check_field для каждого поля. Это позволит сократить объем кода и унифицировать проверку каждой записи.

2023-11-11 05:38 UTC, alxmcs reviewed
Зачтено

2023-11-11 05:38 UTC, closed without merging