6312 Rhj
itsecd/ptm-2 pull request #40
Opened 2023-11-11 05:10 UTC by alxmcs

2023-11-16 19:40 UTC, c0de1sl1fe requested changes
Общие замечания:
- Слишком много комментариев
- Отсутствует логгирование 
- Нарушается `srp`, вместо нескольких функций, уместнее было бы сделать функции генерации, функции записи, с функциями шифрования и дешифрования

2023-11-16 19:40 UTC, c0de1sl1fe commented on main.py
> +        symmetric_file = symmetric_key_path + '\\key.txt'
Issue: эта конструкция может не работать на других платформах 
Point: на разных операционных системах по-разному пишутся пути, плюс корректнее писать именно через join
Solution: лучше использовать os.path.join

2023-11-16 19:40 UTC, c0de1sl1fe commented on main.py
> +    symmetric_file = symmetric_key_path + '\\key.txt'
Issue: эта конструкция может не работать на других платформах 
Point: на разных операционных системах по-разному пишутся пути, плюс корректнее писать именно через join
Solution: лучше использовать os.path.join

2023-11-16 19:40 UTC, c0de1sl1fe commented on main.py
> +    symmetric_file = symmetric_key_path + '\\key.txt'
Issue: эта конструкция может не работать на других платформах 
Point: на разных операционных системах по-разному пишутся пути, плюс корректнее писать именно через join
Solution: лучше использовать os.path.join

2023-11-16 19:40 UTC, c0de1sl1fe commented on main.py
> +                    dest='symmetric_key_path')
Issue: в help прописано, что обязательный аргумент, а проверки нет
Point: без параметра программа работать не сможет 
Solution: прописать required=True

2023-11-16 19:40 UTC, c0de1sl1fe commented on main.py
> +                    dest='decrypted_file_path')
Issue: в help прописано, что обязательный аргумент, а проверки нет
Point: без параметра программа работать не сможет 
Solution: прописать required=True

2023-11-17 08:38 UTC, alxmcs reviewed
Зачтено

2023-11-17 08:38 UTC, closed without merging