6313 Федоров
itsecd/ptm-2 pull request #41
Opened 2023-11-11 05:16 UTC by alxmcs

Это часть кода по автоматизации экспериментов одного из моих дипломников, написанная около 4 лет назад. В ревью хотелось бы увидеть предложения по декомпозиции и рефакторингу кода.

2023-11-14 15:23 UTC, BIOhazzardMTV requested changes
Общие замечания: заменить конкатенацию строк при написании пути функцией os.path.join; использовать f-строки для лучшей читаемости кода; декомпозировать код в соответствии с комментариями.

2023-11-14 15:23 UTC, BIOhazzardMTV commented on 09. pyramid - BILINEAR.py
> +            f.write("SKO№%s:\t%s\tExecution time %s\n" % (i, sko_arr[i - 1], time_arr[i - 1]))
Использовать f-строки здесь и далее по коду

2023-11-14 15:23 UTC, BIOhazzardMTV commented on 10. cross correlation - Cross Correlation Shifts.py
> +        (corrected_image - np.min(corrected_image)) / (np.max(corrected_image) - np.min(corrected_image)))
Вынести в отдельную функцию

2023-11-14 15:23 UTC, BIOhazzardMTV commented on 10. cross correlation - Cross Correlation Shifts.py
> +    sko_arr[i - 1] /= float(ref_image.shape[0] * ref_image.shape[1])
Объединить в одну строку

2023-11-15 07:45 UTC, alxmcs reviewed
Хотелось бы увидеть некоторое саммари по предлагаемым модификациям кода - сколько оставить модулей, какие создать функции, с какими входными параметрами, как решить проблему дублирования кода в модулях.

2023-11-15 13:37 UTC, BIOhazzardMTV commented
Поскольку множество кода здесь дублируется, можно объединить модули и создать общие функции.

В новом модуле могут находиться следующие общие функции (в скобочках - возможные входные параметры): 
- Создание директории, куда будут сохраняться файлы (путь к директории); 
- Функция преобразования изображения с использованием img_as_ubyte (путь до изображения); 
- Функции обработки изображений (путь до файла, эталонное изображение, метод согласования). В ней же будет находиться расчет СКО и запись его в файл.

Также стоит создать функции согласования изображений (для первого файла это строки 30-34, для второго 26-30). В качестве входных параметров можно использовать путь до файла и эталонное изображение)

2023-11-15 13:56 UTC, BIOhazzardMTV requested changes
Разбил код на функции. Во втором модуле можно удалить повторяющийся код.

2023-11-15 13:56 UTC, BIOhazzardMTV commented on 09. pyramid - BILINEAR.py
> +if not os.path.exists(pathOut): os.makedirs(pathOut)  # создать путь, если ещё нет
Вынести в функцию создания директории

2023-11-15 13:56 UTC, BIOhazzardMTV commented on 09. pyramid - BILINEAR.py
> +ref_image = img_as_ubyte(rgb2gray(io.imread(join(pathIn, files[0]))))  # задаём эталон
Вынести в функцию преобразования изображения

2023-11-15 13:56 UTC, BIOhazzardMTV commented on 09. pyramid - BILINEAR.py
> +print(str(time_arr[len(files) - 2]))
Вынести в функцию обработки изображения

2023-11-15 13:56 UTC, BIOhazzardMTV commented on 09. pyramid - BILINEAR.py
> +        (corrected_image - np.min(corrected_image)) / (np.max(corrected_image) - np.min(corrected_image)))
Вынести в функцию согласования изображений

2023-11-15 13:56 UTC, BIOhazzardMTV commented on 10. cross correlation - Cross Correlation Shifts.py
> +        (corrected_image - np.min(corrected_image)) / (np.max(corrected_image) - np.min(corrected_image)))
Вынести в функцию согласования изображений

2023-11-15 13:59 UTC, alxmcs reviewed
Зачтено

2023-11-15 13:59 UTC, closed without merging