6313 Митерев
itsecd/ptm-2 pull request #5
Opened 2023-10-12 12:46 UTC by alxmcs

В этом коде повсеместно встречается один и тот же codesmell. В ревью его надо определить и предложить варианты от него избавиться в каждом случае, где он встречается.

2023-10-13 11:03 UTC, Dmiterev requested changes

2023-10-13 11:43 UTC, Dmiterev requested changes

2023-10-13 11:43 UTC, Dmiterev commented on handbag.py
> +    if handbag.market_segment == "Traveller":
Здесь лучше использовать elif

2023-10-13 11:43 UTC, Dmiterev commented on handbag.py
> +    if handbag.strap_type == "Shoulder":
Аналогично

2023-10-13 11:43 UTC, Dmiterev commented on handbag.py
> +    else:
Строки 77-79 не имеют смысла

2023-10-13 11:43 UTC, Dmiterev commented on handbag.py
> +        result = True
Если условие на 81 строке выполняется, то result и так уже True

2023-10-16 07:28 UTC, alxmcs reviewed
большинство комментариев относятся к стандартам кодирования, а вот code smell в ревью остался без внимания.

2023-10-16 09:09 UTC, Dmiterev requested changes

2023-10-16 09:09 UTC, Dmiterev commented on handbag.py
> +    if handbag.capacity <= MAX_HANDBAG_CAPACITY and event is not None:
Первое условие заменить на    
if not (...):
        return False
Далее  в условиях на 65 и 66 строке используем if not и присваиваем event.status_code соответствующее значение.
Если выполняется if not response, то return false
В конце убрать условие на 81 строке, но оставить то, что под ним кроме 85 строки.

2023-10-16 09:16 UTC, Dmiterev requested changes

2023-10-16 09:16 UTC, Dmiterev commented on handbag.py
> +        event.status_code = "Good"
Здесь лучше event.status_code = "Good" убрать с 93, 97 и 101 строк в начало функции, чтобы сократить код.

2023-10-16 09:21 UTC, Dmiterev requested changes

2023-10-16 09:21 UTC, Dmiterev commented on handbag.py
> +        event.type = 1
Также можно сразу возвращать event.payload в каждом условии, чтобы не проходить следующие

2023-10-16 11:45 UTC, alxmcs reviewed
Зачтено

2023-10-16 11:45 UTC, closed without merging