6311 Балдин
itsecd/ptm-2 pull request #52
Opened 2023-11-30 17:06 UTC by alxmcs

Это классическая kata для рефакторинга. Думаю, codesmell тут очевиден. В ревью необходимо описать проблемы кода и предложить пути его рефакторинга. С примерами кода, где это необходимо

2023-12-07 20:48 UTC, Nikita-Baldin commented on funding_raised.py
Дублирование кода: Код для фильтрации данных по различным критериям (company_name, city, state, round) дублируется в методах where и find_by. Это усложняет поддержку и расширение кода.

Предложение: Вынесите общую логику фильтрации в отдельную функцию, чтобы избежать дублирования кода.
```python
def filter_data(csv_data, options):
  result = []
  for row in csv_data:
    match = True
    for key, value in options.items():
      if row[column_index[key]] != value:
        match = False
        break
      if match:
       result.append(row)
  return result
```

2023-12-09 07:52 UTC, alxmcs reviewed
В ревью описаны далеко не все проблемы декомпозиции кода и его оформления

2023-12-09 07:52 UTC, alxmcs commented on funding_raised.py
Невооруженным взглядом видно, что этот комментарий и пример кода (очевидно, неработающий) был сгенерен чатГПТ. Я бы хотел убедиться, что у тебя имеется доступ к естественному интеллекту помимо искусственного.

В следующем твоем ревью я ожидаю увидеть вменяемый пример отрефакторенного кода в комментарии к строкам кода, где он должен заменить существующий.

2023-12-17 20:56 UTC, Nikita-Baldin requested changes

2023-12-17 20:56 UTC, Nikita-Baldin commented on funding_raised.py
> +      mapped = {}
Вместо того, чтобы несколько раз прописывать mapped можно сделать отдельный словарь
column_mapping = {
        'permalink': 0,
        'company_name': 1,
        'number_employees': 2,
        'category': 3,
        'city': 4,
        'state': 5,
        'funded_date': 6,
        'raised_amount': 7,
        'raised_currency': 8,
        'round': 9
    }

2023-12-17 20:56 UTC, Nikita-Baldin commented on funding_raised.py
> +    if 'company_name' in options:
Можно обьединить фильтрацию, тем самым оптимизировав код
for row in data:  
            if all(options.get(key) == row[column_mapping[key]] for key in options):
                mapped = {key: row[column_mapping[key]] for key in column_mapping}
                output.append(mapped)

2023-12-17 20:56 UTC, Nikita-Baldin commented on funding_raised.py
> +    if 'city' in options:
Можно обьединить фильтрацию, тем самым оптимизировав код
for row in data:  
            if all(options.get(key) == row[column_mapping[key]] for key in options):
                mapped = {key: row[column_mapping[key]] for key in column_mapping}
                output.append(mapped)

2023-12-17 20:56 UTC, Nikita-Baldin commented on funding_raised.py
> +    if 'state' in options:
Можно обьединить фильтрацию, тем самым оптимизировав код
for row in data:  
            if all(options.get(key) == row[column_mapping[key]] for key in options):
                mapped = {key: row[column_mapping[key]] for key in column_mapping}
                output.append(mapped)

2023-12-17 20:56 UTC, Nikita-Baldin commented on funding_raised.py
> +    if 'round' in options:
Можно обьединить фильтрацию, тем самым оптимизировав код
for row in data:  
            if all(options.get(key) == row[column_mapping[key]] for key in options):
                mapped = {key: row[column_mapping[key]] for key in column_mapping}
                output.append(mapped)

2023-12-17 20:56 UTC, Nikita-Baldin commented on funding_raised.py
> +          mapped = {}
Вместо того, чтобы несколько раз прописывать mapped можно сделать отдельный словарь
column_mapping = {
'permalink': 0,
'company_name': 1,
'number_employees': 2,
'category': 3,
'city': 4,
'state': 5,
'funded_date': 6,
'raised_amount': 7,
'raised_currency': 8,
'round': 9
}

2023-12-17 20:56 UTC, Nikita-Baldin commented on funding_raised.py
> +        if row[4] == options['city']:
Вместо того, чтобы несколько раз прописывать mapped можно сделать отдельный словарь
column_mapping = {
'permalink': 0,
'company_name': 1,
'number_employees': 2,
'category': 3,
'city': 4,
'state': 5,
'funded_date': 6,
'raised_amount': 7,
'raised_currency': 8,
'round': 9
}

2023-12-17 20:56 UTC, Nikita-Baldin commented on funding_raised.py
> +          mapped = {}
Вместо того, чтобы несколько раз прописывать mapped можно сделать отдельный словарь
column_mapping = {
'permalink': 0,
'company_name': 1,
'number_employees': 2,
'category': 3,
'city': 4,
'state': 5,
'funded_date': 6,
'raised_amount': 7,
'raised_currency': 8,
'round': 9
}

2023-12-17 20:56 UTC, Nikita-Baldin commented on funding_raised.py
> +          mapped = {}
Вместо того, чтобы несколько раз прописывать mapped можно сделать отдельный словарь
column_mapping = {
'permalink': 0,
'company_name': 1,
'number_employees': 2,
'category': 3,
'city': 4,
'state': 5,
'funded_date': 6,
'raised_amount': 7,
'raised_currency': 8,
'round': 9
}

2023-12-17 20:56 UTC, Nikita-Baldin commented on funding_raised.py
> +    if 'company_name' in options:
Можно обьединить фильтрацию, тем самым оптимизировав код
for row in data:
if all(options.get(key) == row[column_mapping[key]] for key in options):
mapped = {key: row[column_mapping[key]] for key in column_mapping}
return mapped

2023-12-17 20:56 UTC, Nikita-Baldin commented on funding_raised.py
> +    if 'city' in options:
Можно обьединить фильтрацию, тем самым оптимизировав код
for row in data:
if all(options.get(key) == row[column_mapping[key]] for key in options):
mapped = {key: row[column_mapping[key]] for key in column_mapping}
return mapped

2023-12-17 20:56 UTC, Nikita-Baldin commented on funding_raised.py
> +    if 'state' in options:
Можно обьединить фильтрацию, тем самым оптимизировав код
for row in data:
if all(options.get(key) == row[column_mapping[key]] for key in options):
mapped = {key: row[column_mapping[key]] for key in column_mapping}
return mapped

2023-12-17 20:56 UTC, Nikita-Baldin commented on funding_raised.py
> +    if 'round' in options:
Можно обьединить фильтрацию, тем самым оптимизировав код
for row in data:
if all(options.get(key) == row[column_mapping[key]] for key in options):
mapped = {key: row[column_mapping[key]] for key in column_mapping}
return mapped

2023-12-18 04:19 UTC, alxmcs reviewed
Из 13 комментариев последнего ревью уникальными являются только 2. Видимо, это максимум, которого можно от тебя добиться. 

Похоже, мне придется это зачесть, чтобы не издеваться дальше, в первую очередь, над самим  собой.

2023-12-18 04:19 UTC, closed without merging