6313 Казаков
itsecd/ptm-2 pull request #6
Opened 2023-10-13 06:43 UTC by alxmcs

Классическая kata для рефакторинга. Напоминаю, что в ревью должны содержаться конкретные предложения по превращению этого глубоко спидозного кода во вменяемый.

2023-10-15 12:21 UTC, Gironape requested changes
Общие замечания:
1. Нет докстрингов и Type Hints
2. Огромная куча непонятных условий

2023-10-15 12:21 UTC, Gironape commented on tennis.py
> +            result = P1res + "-" + P2res
Можно вынести этот result из условия, чтобы он был конечной записью, тогда все другие копии result можно удалить

2023-10-15 12:21 UTC, Gironape commented on tennis.py
> +            result = P1res + "-" + P2res
Почему бы не объединить два больших условия в одно, добавив оператор or

2023-10-15 12:21 UTC, Gironape commented on tennis.py
> +            P1res = "Love"
убрать это, а также такую же запись для P2res, и присвоить значения "Love" этим переменным в их инициализации

2023-10-16 07:37 UTC, alxmcs reviewed
Code smell в коде был успешно обнаружен. Но хотелось бы побольше конкретики в описании того, как убрать его из кода.

2023-10-16 07:37 UTC, alxmcs commented on tennis.py
> +    def score(self):
В ревью хотелось бы увидеть более конкретные предложения по упрощению сравнений в этом методе.

2023-10-16 16:24 UTC, Gironape requested changes
![код](https://github.com/itsecd/ptm-2/assets/115278933/e68e6ec7-bec1-4b21-8b12-d4dc65269662)
Я понимаю, что, возможно, мой код выглядит тоже "спидозно", но мне кажется, что такое решение выглядит более лучшим, чем представленное на ревью
К тому же я понимаю, что должен был сказать, что нужно исправить, а не пытаться исправить самому, но я же не преподаватель, а мне практика с классами в питоне никогда не помешает)))
Надеюсь, что смог хоть немного улучшить код и удовлетворить ваши требования

2023-10-16 16:24 UTC, Gironape commented on tennis.py
> +        self.p2points +=1
При всей моей погруженности в решении проблемы данного кода, я смог придумать только один наиболее верный, по моему мнению, вариант:
Реализовать класс, как игрока, а не как теннисную игру, но сохраняя всю логику, которую я смог увидеть в этом коде. Нужно просто добавить несколько методов класса, которые будут реализовывать все, что необходимо ( свой код с решением я приложу)

2023-10-16 16:26 UTC, Gironape commented
![image](https://github.com/itsecd/ptm-2/assets/115278933/66f9c235-2cb4-44f7-9a5b-66e23960769a)

2023-10-16 16:35 UTC, Gironape commented
С другой стороны, проанализировав свой код, я понял, что все эти методы можно без труда засунуть и в класс TennisGame, и тогда все проблемы уйдут 👍

2023-10-17 07:28 UTC, alxmcs reviewed
Зачтено

2023-10-17 07:28 UTC, closed without merging