6313 Жидяев
itsecd/ptm-2 pull request #7
Opened 2023-10-13 06:47 UTC by alxmcs

Это класическая kata для рефакторинга. В ревью надо указать, какие code smell тут присутствуют и как от них избавиться (желательно с примерами кода).

2023-10-13 10:54 UTC, Dmitrii14 commented on yatzy.py
> +class Yatzy:
Нет docstring у класса

2023-10-13 10:54 UTC, Dmitrii14 commented on yatzy.py
> +
Лишний пробел

2023-10-13 10:57 UTC, Dmitrii14 commented on yatzy.py
> +    def chance(d1, d2, d3, d4, d5):
Нет Type Hints и  docstring

2023-10-13 10:58 UTC, Dmitrii14 commented on yatzy.py
> +        total += d1
Было бы логично написать все суммирования в одну строчку

2023-10-13 10:58 UTC, Dmitrii14 commented on yatzy.py
> +    def yatzy(dice):
Аналогично нет Type Hints и docstring

2023-10-13 10:59 UTC, Dmitrii14 commented on yatzy.py
> +        counts = [0]*(len(dice)+1)
Вокруг операторов должны быть отступы

2023-10-13 11:00 UTC, Dmitrii14 commented on yatzy.py
> +            counts[die-1] += 1
Аналогично

2023-10-13 11:01 UTC, Dmitrii14 commented on yatzy.py
> +    def ones( d1,  d2,  d3,  d4,  d5):
Аналогично нет Type Hints и docstring и лишний отступ перед передаваемыми элементами

2023-10-13 11:05 UTC, Dmitrii14 commented on yatzy.py
> +        if (d1 == 1):
d_list = [d1, d2, d3, d4, d5]
sum = sum(value == 1 for value in d_list)

Такой подход делает код более кратким и облегчает добавление или удаление переменных в будущем.

2023-10-13 11:06 UTC, Dmitrii14 commented on yatzy.py
> +
Лишний отступ

2023-10-13 11:06 UTC, Dmitrii14 commented on yatzy.py
> +
Лишний отступ

2023-10-13 11:07 UTC, Dmitrii14 commented on yatzy.py
> +    def twos( d1,  d2,  d3,  d4,  d5):
Аналогично нет Type Hints и docstring и лишний отступ перед передаваемыми элементами

2023-10-13 11:07 UTC, Dmitrii14 commented on yatzy.py
> +        if (d1 == 2):
Аналогично упростить

2023-10-13 11:16 UTC, Dmitrii14 commented on yatzy.py
> +    def twos( d1,  d2,  d3,  d4,  d5):
Эта функция идентична функции ones, можно объединить их

2023-10-13 11:16 UTC, Dmitrii14 commented on yatzy.py
> +    def threes( d1,  d2,  d3,  d4,  d5):
Аналогично

2023-10-13 11:17 UTC, Dmitrii14 commented on yatzy.py
> +
Лишний отступ

2023-10-13 11:20 UTC, Dmitrii14 commented on yatzy.py
> +    def __init__(self, d1, d2, d3, d4, _5):
Инициализатор переменных  должен быть  в начале класса, опечатка вместо d5 записывается _5

2023-10-13 11:31 UTC, Dmitrii14 commented on yatzy.py
> +    def fours(self):
Аналогично нет Type Hints и docstring 

Данную функцию нужно сделать более универсальной (то есть принимать некоторое значение, которое потом будет сравниваться)
def sum_and_checking(self, value: int) -> int:

2023-10-13 11:32 UTC, Dmitrii14 commented on yatzy.py
> +    def fives(self):
Аналогично

2023-10-13 11:33 UTC, Dmitrii14 commented on yatzy.py
> +            if (self.dice[at] == 6):
Аналогично

2023-10-13 11:33 UTC, Dmitrii14 commented on yatzy.py
> +    def sixes(self):
Аналогично

2023-10-13 11:42 UTC, Dmitrii14 commented on yatzy.py
> +    def score_pair( d1,  d2,  d3,  d4,  d5):
Аналогично нет Type Hints и docstring и лишний отступ перед передаваемыми элементами

Упростить и сделать более универсальную функцию

2023-10-13 11:42 UTC, Dmitrii14 commented on yatzy.py
> +        counts = [0]*6
Вокруг операторов должны быть отступы

2023-10-13 11:42 UTC, Dmitrii14 commented on yatzy.py
> +        counts[d1-1] += 1
Аналогично

2023-10-13 11:42 UTC, Dmitrii14 commented on yatzy.py
> +        counts[d2-1] += 1
Аналогично

2023-10-13 11:42 UTC, Dmitrii14 commented on yatzy.py
> +        counts[d3-1] += 1
Аналогично

2023-10-13 11:43 UTC, Dmitrii14 commented on yatzy.py
> +        counts[d4-1] += 1
Аналогично

2023-10-13 11:43 UTC, Dmitrii14 commented on yatzy.py
> +        counts[d5-1] += 1
Аналогично

2023-10-13 11:43 UTC, Dmitrii14 commented on yatzy.py
> +            if (counts[6-at-1] == 2):
Аналогично

2023-10-13 11:43 UTC, Dmitrii14 commented on yatzy.py
> +                return (6-at)*2
Аналогично

2023-10-13 11:44 UTC, Dmitrii14 commented on yatzy.py
> +    def two_pair( d1,  d2,  d3,  d4,  d5):
Объединить  с предыдущей функцией

2023-10-13 11:51 UTC, Dmitrii14 commented on yatzy.py
> +    def four_of_a_kind( _1,  _2,  d3,  d4,  d5):
Аналогично нет Type Hints и docstring, опечатка вместо _1 и _2 должно быть d1 и d2

Сделать функцию универсальной (то есть принимать некоторое значение, которое потом будет сравниваться)

2023-10-13 11:52 UTC, Dmitrii14 commented on yatzy.py
> +
Лишний отступ

2023-10-13 11:52 UTC, Dmitrii14 commented on yatzy.py
> +    def three_of_a_kind( d1,  d2,  d3,  d4,  d5):
Аналогично

2023-10-13 11:53 UTC, Dmitrii14 commented on yatzy.py
> +
Лишний отступ

2023-10-13 11:53 UTC, Dmitrii14 commented on yatzy.py
> +    def smallStraight( d1,  d2,  d3,  d4,  d5):
Аналогично объединить

2023-10-13 11:53 UTC, Dmitrii14 commented on yatzy.py
> +
Лишний отступ

2023-10-13 11:54 UTC, Dmitrii14 commented on yatzy.py
> +    def largeStraight( d1,  d2,  d3,  d4,  d5):
Аналогично объединить с предыдущей

2023-10-13 11:54 UTC, Dmitrii14 commented on yatzy.py
> +
Лишний отступ

2023-10-13 11:55 UTC, Dmitrii14 commented on yatzy.py
> +        _2 = False
ЧТО ЭТО ТАКОЕ??? 
![image](https://github.com/itsecd/ptm-2/assets/117352471/42d20409-6706-4acf-aafe-62b8ecd480cb)

2023-10-13 11:55 UTC, Dmitrii14 commented on yatzy.py
> +
Лишний отступ

2023-10-13 11:56 UTC, Dmitrii14 commented on yatzy.py
> +        tallies = [0]*6
Вокруг операторов должны быть отступы

2023-10-13 11:56 UTC, Dmitrii14 commented on yatzy.py
> +        tallies[d1-1] += 1
Аналогично

2023-10-13 11:56 UTC, Dmitrii14 commented on yatzy.py
> +        tallies[d2-1] += 1
Аналогично

2023-10-13 11:56 UTC, Dmitrii14 commented on yatzy.py
> +        tallies[d3-1] += 1
Аналогично

2023-10-13 11:56 UTC, Dmitrii14 commented on yatzy.py
> +        tallies[d4-1] += 1
Аналогично

2023-10-13 11:56 UTC, Dmitrii14 commented on yatzy.py
> +        tallies[d5-1] += 1
Аналогично

2023-10-13 11:57 UTC, Dmitrii14 commented on yatzy.py
> +
Лишний отступ

2023-10-13 11:59 UTC, Dmitrii14 commented on yatzy.py
> +    def fullHouse( d1,  d2,  d3,  d4,  d5):
Аналогично нет Type Hints и docstring

2023-10-13 11:59 UTC, Dmitrii14 commented on yatzy.py
> +        _2 = False
Неправильное название переменной

2023-10-13 11:59 UTC, Dmitrii14 commented on yatzy.py
> +        _2 = False
Неправильное название переменной

2023-10-13 11:59 UTC, Dmitrii14 commented on yatzy.py
> +        _2_at = 0
Неправильное название переменной

2023-10-13 12:00 UTC, Dmitrii14 commented on yatzy.py
> +        _3 = False
Неправильное название переменной

2023-10-13 12:00 UTC, Dmitrii14 commented on yatzy.py
> +        _3_at = 0
Неправильное название переменной

2023-10-13 12:00 UTC, Dmitrii14 commented on yatzy.py
> +                _2_at = i+1
Вокруг операторов должны быть отступы

2023-10-13 12:00 UTC, Dmitrii14 commented on yatzy.py
> +
Лишний отступ

2023-10-13 12:00 UTC, Dmitrii14 commented on yatzy.py
> +
Лишний отступ

2023-10-13 12:01 UTC, Dmitrii14 commented on yatzy.py
> +                _3_at = i+1
Вокруг операторов должны быть отступы

2023-10-13 12:01 UTC, Dmitrii14 commented on yatzy.py
> +
Лишний отступ

2023-10-13 12:01 UTC, Dmitrii14 commented on yatzy.py
> +
Лишний отступ

2023-10-13 12:05 UTC, Dmitrii14 commented on yatzy.py
> +        if (d2 == 1):
Не нужны скобки

2023-10-13 12:05 UTC, Dmitrii14 commented on yatzy.py
> +        if (d3 == 1):
Аналогично

2023-10-13 12:05 UTC, Dmitrii14 commented on yatzy.py
> +        if (d4 == 1):
Аналогично

2023-10-13 12:05 UTC, Dmitrii14 commented on yatzy.py
> +        if (d5 == 1):
Аналогично

2023-10-13 12:08 UTC, Dmitrii14 requested changes
Этот код просто идеальный пример того, как НЕ нужно писать программы. Я в шоке от того, какие тут грязные трюки и плохие практики. Начнем с того, что я даже не могу определить, что этот класс делает. Названия переменных и методов - это просто космос! Большинство функций это копирование предыдущих, можно объединить их друг с другом.  Вот мои эмоции после рефакторинга этого кода
![image](https://github.com/itsecd/ptm-2/assets/117352471/c007ceaf-dbef-41c0-a4eb-47d18cad21f8)

2023-10-16 07:51 UTC, alxmcs reviewed
На будущее:
![image](https://github.com/itsecd/ptm-2/assets/70561974/54b9c347-9eda-454e-9241-a4a582732be8)
Нужно было жать на правую кнопку, а не на левую.


В целом, помимо проблем с оформлением кода, в ревью были упомянуты и архитектурные проблемы. Для одного набора проблемных методов даже был приведен пример кода.

2023-10-16 07:51 UTC, alxmcs commented on yatzy.py
> +    def two_pair( d1,  d2,  d3,  d4,  d5):
А вот для второго набора методов примера кода не приведено

2023-10-16 08:38 UTC, Dmitrii14 requested changes
Добавил пример для улучшения и универсализации функции

2023-10-16 08:38 UTC, Dmitrii14 commented on yatzy.py
> +    def two_pair( d1,  d2,  d3,  d4,  d5):
Вот пример, как можно упростить этот код и сделать его более универсальным
 n = sum(count >= 2 for count in counts)
 score = sum((6 - i) * (counts[6 - i - 1] // 2) for i in range(6))
 return score if n == 2 else 0

2023-10-16 11:44 UTC, closed without merging