6313
itsecd/ptm-2 pull request #9
Opened 2023-10-13 07:02 UTC by alxmcs

2023-10-21 12:25 UTC, daryaskhrv commented
Стандарты кодирования: следует добавить типы переменных и возвращаемых значений, а также - докстринги

2023-10-21 12:33 UTC, daryaskhrv commented
Касаемо декомпозиции - 8 функций фильтраций практически идентичны, за исключением самих методов фильтраций. Предлагаю объединить их в одну функцию, что сократит код +- в 4 раза. Например, так:

```py
def image_filter(files, progress_bar, progress_label, root, filter_type):
    progress_step = 100 / len(files)
    progress_bar['value'] = 0
    progress_label.config(text="0")
    root.update_idletasks()
    result_array = []
    for i in tqdm(range(0, len(files)), desc="Фильтрация: "):
        if filter_type == "Винер":
            img = img_as_float(rgb2gray(files[i]))
            restored_img, _ = restoration.unsupervised_wiener(img, (np.ones((5, 5)) / 25))
            restored_img = img_as_ubyte(
                (restored_img - np.min(restored_img)) / (np.max(restored_img) - np.min(restored_img)))
        elif filter_type == "Гаусс":
            restored_img = ndimage.gaussian_filter(files[i], 2)
        elif filter_type == "Медианный":
            restored_img = ndimage.median_filter(files[i], 3)
        elif filter_type == "Контраст":
            clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
            restored_img = clahe.apply(files[i])
        elif filter_type == "Резкость":
            sharpen_mask = np.array([[-1, -1, -1],
                                     [-1, 9, -1],
                                     [-1, -1, -1]])
            restored_img = cv2.filter2D(files[i], -1, sharpen_mask)
        elif filter_type == "Шумоподавление":
            patch_kw = dict(patch_size=2, patch_distance=2)
            sigma_est = np.mean(estimate_sigma(files[i]))
            img = img_as_float(files[i])
            restored_img = denoise_nl_means(img, h=0.8 * sigma_est, sigma=sigma_est, fast_mode=False, **patch_kw)
            restored_img = img_as_ubyte(
                (restored_img - np.min(restored_img)) / (np.max(restored_img) - np.min(restored_img)))
        elif filter_type == "Обратная свёртка":
            img = img_as_float(rgb2gray(files[i]))
            restored_img = restoration.richardson_lucy(img, (np.ones((3, 3)) / 25))
            restored_img = img_as_ubyte(
                (restored_img - np.min(restored_img)) / (np.max(restored_img) - np.min(restored_img)))
        elif filter_type == "Вейвлет":
            img = img_as_float(rgb2gray(files[i]))
            restored_img = denoise_wavelet(img, rescale_sigma=True)
            restored_img = img_as_ubyte(
                (restored_img - np.min(restored_img)) / (np.max(restored_img) - np.min(restored_img)))
        else:
            print('Неправильно указан тип фильтра')
            return
        result_array.append(restored_img)
        progress_bar['value'] += progress_step
        progress_label.config(text=round(progress_bar['value']))
        root.update_idletasks()
    progress_bar['value'] = 100
    progress_label.config(text=progress_bar['value'])
    root.update_idletasks()
    return result_array
```

Тогда вызов этой функции может происходить так:

```py
def filtration_gui_main(files, mode, progress_bar_info):
    result_array = []
    if mode == "Без предобработки":
        result_array = files
    else:
        result_array = image_filter(files, progress_bar_info[0], progress_bar_info[1], progress_bar_info[2], mode)
    return result_array
```

Это значительно упростит код и его восприятие

2023-10-21 12:33 UTC, daryaskhrv requested changes

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +# from skimage import io
Убрать неиспользуемый импорт

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +from skimage.color import rgb2gray
Все импорты должны быть в начале файла. Сгруппировать по pep8: стандартные библиотеки; сторонние; локальные модули проекта. Группы разделяются пустыми строками

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +    from skimage import restoration
Импорт - в начало файла

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +            (restored_img - np.min(restored_img)) / (np.max(restored_img) - np.min(restored_img)))
Длина строки превышает 79 символов

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +        # io.imsave("temp/" + str(i) + ".jpg", restored_img)
Убрать комментарий

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +    from scipy import ndimage
Импорт - в начало файла

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +        # io.imsave("temp/" + str(i) + ".jpg", restored_img)
Убрать комментарий

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +    from scipy import ndimage
Импорт - в начало файла

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +        # io.imsave("temp/" + str(i) + ".jpg", restored_img)
Убрать комментарий

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +    import cv2
Импорт - в начало файла

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +        # io.imsave("temp/" + str(i) + ".jpg", restored_img)
Аналогично: убрать лишний комментарий

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +    import cv2
Аналогично: импорт - в начало файла

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +        # io.imsave("temp/" + str(i) + ".jpg", restored_img)
Аналогично: убрать комментарий

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +    from skimage.restoration import denoise_nl_means, estimate_sigma
Аналогично: импорт - в начало файла

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +        restored_img = denoise_nl_means(img, h=0.8 * sigma_est, sigma=sigma_est, fast_mode=False, **patch_kw)
Длина строки превышает 79 символов

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +        # io.imsave("temp/" + str(i) + ".jpg", restored_img)
Аналогично: убрать комментарий

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +    from skimage import restoration
Аналогично: импорт - в начало файла

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +        # io.imsave("temp/" + str(i) + ".jpg", restored_img)
Аналогично: убрать комментарий

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +    from skimage.restoration import denoise_wavelet
Аналогично: импорт - в начало файла

2023-10-21 12:33 UTC, daryaskhrv commented on filtration.py
> +        # io.imsave("temp/" + str(i) + ".jpg", restored_img)
Аналогично: убрать комментарий

2023-10-23 08:13 UTC, alxmcs reviewed
Зачтено.

Хотя, можно было бы еще больше упростить код и избавиться от многоэтажного elif-а, если повыносить каждый вид обработки в отдельную функцию (все равно параметры в каждой отдельной обработке фиксированные) и соорудить словарь вида 
```py
def gauss(image):
   return ndimage.gaussian_filter(image, 2)

def median(image):
    return ndimage.median_filter(image, 3)
processing = {"Гаусс": gauss, "Медианный": median, ...}
```
чтобы потом просто вызвать
```py
def image_filter(files, progress_bar, progress_label, root, filter_type):
...
   restored_img = processing[filter_type](files[i])
...
```

2023-10-23 08:14 UTC, closed without merging